# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import Field, HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel, WorkerSandboxBackend


class WorkerSettings(BaseSettings):
    model_config = SettingsConfigDict(
        dotenv_filtering="only_existing",
        env_prefix="LOOM_WORKER_",
        env_file=".env",
        extra="forbid",
    )

    artifacts_bucket: str = "artifacts"
    benchmark_cache: Path | None = None
    blocking_io_max_workers: int | None = None
    candidate_sha: str = ""
    cgroup_parent: str = ""
    claim_poll_interval_sec: float = 1.0
    compose_project: str = ""
    container_cpus: float = 0.0
    container_memory_mib: int = 0
    container_pids: int = 0
    control_plane_url: HttpUrl = cast(HttpUrl, "http://loom-control-plane:8080")
    daytona_api_max_concurrent: int = 4
    daytona_api_min_interval_sec: float = 0.25
    daytona_cleanup_interval_sec: float = 30.0
    daytona_sandbox_ttl_sec: int = 86400
    docker_api_timeout_sec: int = 1800
    docker_socket: Path = Path("/var/run/docker.sock")
    drain_timeout_sec: int = 600
    enable_worker_vllm: bool = False
    family_state_download_timeout_sec: float = 120.0
    fixtures_root: Path | None = None
    gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    heartbeat_interval_sec: float = 5.0
    hostname: str | None = None
    idle_exit_after_seconds: float | None = None
    log_level: LogLevel = "info"
    max_concurrent: int = 5
    metrics_port: int = 9090
    minio_access_key: SecretStr
    minio_connect_timeout_sec: float = 5.0
    minio_endpoint: str = "http://loom-minio:9000"
    minio_max_pool_connections: int = 256
    minio_operation_attempts: int = 3
    minio_operation_timeout_sec: float = 300.0
    minio_read_timeout_sec: float = 120.0
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    pipeline_runtime_secrets_dir: Path = Path("/dev/shm")
    pipeline_terminal_task_validator_path: Path = Path("/usr/local/bin/loom-terminal-task-validator")
    pipeline_terminal_task_validator_sha256: str = ""
    pipeline_terminalgen_authoring_enabled: bool = False
    pool_name: str = "default"
    pre_start_heartbeat_interval_sec: float = 60.0
    require_cgroup_parent: bool = False
    sandbox_backend: WorkerSandboxBackend = "docker"
    sandbox_identity: str = ""
    sandbox_isolation: bool = False
    sandbox_singleton_image: str = "loom-llm-gateway-sandbox:dev"
    sandbox_singleton_secrets_dir: str = "/var/lib/loom/sandbox-secrets"
    sandbox_step_jwt_ttl_sec: int = 600
    sandbox_worker_index: int = 0
    setup_health_dstate_max: int = 32
    setup_health_guard_enabled: bool = True
    setup_health_io_full_avg10_max: float = 50.0
    setup_health_min_mem_available_mb: int = 2048
    setup_health_min_swap_free_mb: int = 1024
    setup_health_poll_interval_sec: float = 5.0
    setup_health_wait_timeout_sec: float = 300.0
    slurm_allocated_gpus: int = -1
    slurm_gpu_device_ids: str = ""
    slurm_job_id: str = ""
    storage_auth_kind: str = "static_keys"
    storage_backend: str = "minio"
    subprocess_gateway_url: HttpUrl | None = None
    task_image_build_max_bytes: int = Field(default=536870912, validation_alias="LOOM_TASK_IMAGE_BUILD_MAX_BYTES")
    task_image_build_max_files: int = Field(default=2000, validation_alias="LOOM_TASK_IMAGE_BUILD_MAX_FILES")
    task_image_builder_idle_exit_seconds: int = 120
    task_image_local_ttl_hours: int = 168
    task_image_min_free_gb: int = 20
    task_materialize_timeout_sec: float = 300.0
    token: SecretStr
    trajectories_bucket: str = "trajectories"
    trajectory_cache_dir: Path = Path("/var/lib/loom/trajectories")
    trial_cache_base_image_pull_timeout_sec: float = 1800.0
    trial_cache_build_lock_timeout_sec: float = 1800.0
    trial_cache_build_max_concurrent: int = 1
    trial_cache_min_free_gb: int = 20
    trial_cache_registry_pull_timeout_sec: float = 15.0
    trial_cache_registry_repo: str = ""
    trial_cache_ttl_hours: int = 168
    trial_cancel_poll_interval_sec: float = 30.0
    trial_hard_deadline_grace_sec: float = 600.0
    trial_hard_deadline_multiplier: float = 3.0
    vllm_gpu_memory_utilization: float = 0.9
    vllm_tensor_parallel_size: int = 1


WorkerSettings.model_rebuild()
