# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class WorkerSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="LOOM_WORKER_", env_file=".env", extra="forbid",
    )

    benchmark_cache: Path | None = None
    claim_poll_interval_sec: float = 1.0
    control_plane_url: HttpUrl = cast(HttpUrl, "http://loom-control-plane:8080")
    docker_socket: Path = Path("/var/run/docker.sock")
    drain_timeout_sec: int = 600
    enable_worker_vllm: bool = False
    fixtures_root: Path | None = None
    gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    heartbeat_interval_sec: float = 5.0
    log_level: LogLevel = "info"
    max_concurrent: int = 5
    metrics_port: int = 9090
    minio_access_key: SecretStr
    minio_endpoint: str = "http://loom-minio:9000"
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    sandbox_isolation: bool = False
    sandbox_singleton_image: str = "loom-llm-gateway-sandbox:dev"
    sandbox_singleton_secrets_dir: str = "/var/lib/loom/sandbox-secrets"
    sandbox_worker_index: int = 0
    token: SecretStr
    trajectory_cache_dir: Path = Path("/var/lib/loom/trajectories")
    vllm_gpu_memory_utilization: float = 0.9
    vllm_tensor_parallel_size: int = 1


WorkerSettings.model_rebuild()
