# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class WorkerSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="LOOM_WORKER_", env_file=".env", extra="forbid",
    )

    benchmark_cache: Path | None = None
    blocking_io_max_workers: int | None = None
    claim_poll_interval_sec: float = 1.0
    control_plane_url: HttpUrl = cast(HttpUrl, "http://loom-control-plane:8080")
    docker_api_timeout_sec: int = 1800
    docker_socket: Path = Path("/var/run/docker.sock")
    drain_timeout_sec: int = 600
    enable_worker_vllm: bool = False
    fixtures_root: Path | None = None
    gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    heartbeat_interval_sec: float = 5.0
    hostname: str | None = None
    idle_exit_after_seconds: float | None = None
    log_level: LogLevel = "info"
    max_concurrent: int = 5
    metrics_port: int = 9090
    minio_access_key: SecretStr
    minio_connect_timeout_sec: float = 5.0
    minio_endpoint: str = "http://loom-minio:9000"
    minio_max_pool_connections: int = 256
    minio_operation_attempts: int = 3
    minio_operation_timeout_sec: float = 300.0
    minio_read_timeout_sec: float = 120.0
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    pool_name: str = "default"
    sandbox_isolation: bool = False
    sandbox_singleton_image: str = "loom-llm-gateway-sandbox:dev"
    sandbox_singleton_secrets_dir: str = "/var/lib/loom/sandbox-secrets"
    sandbox_step_jwt_ttl_sec: int = 600
    sandbox_worker_index: int = 0
    subprocess_gateway_url: HttpUrl | None = None
    task_image_build_max_bytes: int = 536870912
    task_image_build_max_files: int = 2000
    token: SecretStr
    trajectory_cache_dir: Path = Path("/var/lib/loom/trajectories")
    trial_cache_base_image_pull_timeout_sec: float = 1800.0
    trial_cache_build_lock_timeout_sec: float = 1800.0
    trial_cache_min_free_gb: int = 20
    trial_cache_registry_pull_timeout_sec: float = 15.0
    trial_cache_registry_repo: str = ""
    trial_cache_ttl_hours: int = 168
    vllm_gpu_memory_utilization: float = 0.9
    vllm_tensor_parallel_size: int = 1


WorkerSettings.model_rebuild()
