apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: loom-sandbox
  annotations:
    loom.nebius/runtime-profile-sha256: 0f81e39d7cdd012b61ecb1f9ab17252270209f6bbca3de932e6c978468318f8e
handler: runsc-loom-sandbox
scheduling:
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    loom.nebius/runtime-profile-a: 0f81e39d7cdd012b61ecb1f9ab172522
    loom.nebius/runtime-profile-b: 70209f6bbca3de932e6c978468318f8e
  tolerations:
    - key: loom.nebius/execution
      operator: Equal
      value: "true"
      effect: NoSchedule
