package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"strings"
	"testing"
)

func registeredManifestVector() []RegisteredBundleObject {
	paths := []string{"a\"<&>.txt", "café\u2028\u2029.sh", "\ue000.txt", "😀.txt"}
	files := make([]RegisteredBundleObject, len(paths))
	for i, path := range paths {
		mode := "0644"
		if i%2 != 0 {
			mode = "0755"
		}
		files[i] = RegisteredBundleObject{RelativePath: path, SizeBytes: int64(i), SHA256: fmt.Sprintf("%x", sha256.Sum256(make([]byte, i))), Mode: mode}
	}
	return files
}

func TestRegisteredManifestMatchesIndependentPythonRFC8785AndLegacyModeVectors(t *testing.T) {
	files := registeredManifestVector()
	// Independently generated by TaskImageBundleContentManifestV1/rfc8785 and
	// Python sorted ensure_ascii mode JSON. BMP-before-astral file ordering is
	// Python codepoint order; the files array is not sorted as UTF16 object keys.
	const modes = "a035ff1f504fa372da12d29a7c95d7641915ef59bb2d2f74c2d90a3e45c64b3c"
	const manifest = "cb43cfc9ffa01829856e09529fdae263027daa520d680575005f2e2ecf90edbc"
	payload, metadata, err := registeredBundleManifest(files, strings.Repeat("4", 64))
	if err != nil {
		t.Fatal(err)
	}
	if fmt.Sprintf("%x", sha256.Sum256(payload)) != manifest || fmt.Sprintf("%x", sha256.Sum256(metadata)) != modes {
		t.Fatalf("cross-language identity mismatch: manifest=%s modes=%s", payload, metadata)
	}
	if bytes.Contains(payload, []byte(`\u2028`)) || bytes.Contains(payload, []byte(`\u003c`)) || !bytes.Contains(metadata, []byte(`\ud83d\ude00`)) {
		t.Fatal("canonical manifest and legacy ASCII mode encodings were conflated")
	}
	files[0].URL = "https://example.invalid/transport-secret?signature=never-hashed"
	changed, changedMetadata, err := registeredBundleManifest(files, strings.Repeat("4", 64))
	if err != nil || !bytes.Equal(payload, changed) || !bytes.Equal(metadata, changedMetadata) {
		t.Fatal("transport URL changed content identity")
	}
}

func TestRegisteredManifestRejectsUnsafeOrAmbiguousDescriptors(t *testing.T) {
	for _, kind := range []string{"empty", "sidecar", "relative", "backslash", "control", "del", "invalid_utf8", "long_utf8", "mode", "hash", "negative_size", "byte_limit", "count_limit", "duplicate", "order", "file_directory", "checksum"} {
		t.Run(kind, func(t *testing.T) {
			files := registeredManifestVector()
			checksum := strings.Repeat("4", 64)
			switch kind {
			case "empty":
				files = nil
			case "sidecar":
				files[0].RelativePath = ".loom-bundle-files.v1.json"
			case "relative":
				files[0].RelativePath = "../escape"
			case "backslash":
				files[0].RelativePath = `a\u2028`
			case "control":
				files[0].RelativePath = "a\n"
			case "del":
				files[0].RelativePath = "a\x7f"
			case "invalid_utf8":
				files[0].RelativePath = "a\xff"
			case "long_utf8":
				files[0].RelativePath = strings.Repeat("é", 513)
			case "mode":
				files[0].Mode = "04755"
			case "hash":
				files[0].SHA256 = strings.Repeat("0", 64)
			case "negative_size":
				files[0].SizeBytes = -1
			case "byte_limit":
				files[0].SizeBytes = maxTaskImageBuildBundleBytes
			case "count_limit":
				files = make([]RegisteredBundleObject, 2001)
			case "duplicate":
				files[1] = files[0]
			case "order":
				files[0], files[1] = files[1], files[0]
			case "file_directory":
				files[0].RelativePath, files[1].RelativePath = "a", "a/b"
			case "checksum":
				checksum = strings.Repeat("0", 64)
			}
			if _, _, err := registeredBundleManifest(files, checksum); err == nil {
				t.Fatal("accepted invalid descriptors")
			}
		})
	}
}
