ClusterName=trt-oldlab
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
GresTypes=gpu
NodeName=trt-eai-oldlab-[1-5] Gres=gpu:rtx5080:2 State=UNKNOWN
PartitionName=all Nodes=trt-eai-oldlab-[1-5] Default=NO State=UP OverSubscribe=EXCLUSIVE
