apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: loom-personal-dev-builder
  annotations:
    loom.dev/runtime-profile-sha256: 6ee2c283e5bf0783e192787522ea9550caadff4131590cc0a26dbf7dd2a6869b
handler: runsc-personal-dev
scheduling:
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    loom.dev/personal-dev-runtime-profile-a: 6ee2c283e5bf0783e192787522ea9550
    loom.dev/personal-dev-runtime-profile-b: caadff4131590cc0a26dbf7dd2a6869b
