"""Ordinary runtime access survives sealed ownership without regaining DDL."""

from uuid import uuid4

import psycopg
import pytest
from alembic import command
from alembic.config import Config

from loom.application_runtime_grants import application_runtime_grants_ddl
from tests.integration.test_application_migration_authority import (
    application_migration_roles,  # noqa: F401
)


def _acl_state(connection: psycopg.Connection) -> tuple[object, ...]:
    return tuple(
        connection.execute(query).fetchall()
        for query in (
            "SELECT relname,relacl FROM pg_catalog.pg_class WHERE relnamespace='public'::regnamespace ORDER BY relname",
            "SELECT c.relname,a.attnum,a.attacl FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid WHERE c.relnamespace='public'::regnamespace AND a.attnum>0 ORDER BY 1,2",
            "SELECT nspacl FROM pg_catalog.pg_namespace WHERE nspname='public'",
            "SELECT datacl FROM pg_catalog.pg_database WHERE datname=current_database()",
            "SELECT defaclrole,defaclnamespace,defaclobjtype,defaclacl FROM pg_catalog.pg_default_acl ORDER BY 1,2,3",
        )
    )


@pytest.mark.parametrize("shadow_catalog", [False, True])
def test_runtime_grants_preserve_data_access_and_deny_schema_changes(
    application_migration_roles: tuple[Config, str, str, str],  # noqa: F811
    shadow_catalog: bool,
) -> None:
    cfg, url, owner, migrator = application_migration_roles
    command.upgrade(cfg, "head")
    runtime = owner + "_peer"
    with psycopg.connect(
        url.replace("postgresql+psycopg://", "postgresql://", 1), autocommit=True
    ) as admin:
        admin.execute(
            psycopg.sql.SQL(
                "ALTER ROLE {} NOLOGIN NOINHERIT; REVOKE {} FROM {}; "
                "ALTER ROLE {} NOLOGIN PASSWORD NULL; ALTER SCHEMA public OWNER TO {}"
            ).format(
                *(
                    psycopg.sql.Identifier(role)
                    for role in (runtime, owner, migrator, migrator, owner)
                )
            )
        )
        if shadow_catalog:
            admin.execute(psycopg.sql.SQL("SET ROLE {}").format(psycopg.sql.Identifier(owner)))
            admin.execute(
                "CREATE FUNCTION public.current_database() RETURNS name LANGUAGE plpgsql "
                "AS $$BEGIN RAISE EXCEPTION 'shadow database lookup executed'; END$$"
            )
            admin.execute("RESET ROLE")
            admin.execute("SET search_path=public,pg_catalog")
        statement = application_runtime_grants_ddl(owner_role=owner, runtime_role=runtime)
        admin.execute(statement)
        admin.execute(statement)
        if shadow_catalog:
            assert admin.execute("SHOW search_path").fetchone() == ("public, pg_catalog",)
        admin.execute(psycopg.sql.SQL("SET ROLE {}").format(psycopg.sql.Identifier(owner)))
        admin.execute(
            "CREATE TABLE public.runtime_future (id integer GENERATED BY DEFAULT AS IDENTITY)"
        )
        admin.execute("CREATE SEQUENCE public.runtime_future_sequence")
        admin.execute("RESET ROLE")
        admin.execute(psycopg.sql.SQL("SET ROLE {}").format(psycopg.sql.Identifier(runtime)))
        team_id = uuid4()
        admin.execute("INSERT INTO public.teams(id,name) VALUES (%s,'runtime-grants')", (team_id,))
        admin.execute("UPDATE public.teams SET name='runtime-updated' WHERE id=%s", (team_id,))
        assert admin.execute(
            "SELECT name FROM public.teams WHERE id=%s", (team_id,)
        ).fetchone() == ("runtime-updated",)
        admin.execute("DELETE FROM public.teams WHERE id=%s", (team_id,))
        admin.execute("INSERT INTO public.runtime_future DEFAULT VALUES")
        assert admin.execute("SELECT id FROM public.runtime_future").fetchone() == (1,)
        assert admin.execute("SELECT nextval('public.runtime_future_sequence')").fetchone() == (1,)
        assert admin.execute("SELECT version_num FROM public.alembic_version").fetchone() == (
            "0146",
        )
        for forbidden in (
            "UPDATE public.alembic_version SET version_num=version_num",
            "INSERT INTO public.alembic_version VALUES ('untrusted')",
            "DELETE FROM public.alembic_version",
            "ALTER TABLE public.trials DISABLE TRIGGER ALL",
            "CREATE TABLE public.runtime_escape (id integer)",
            "TRUNCATE public.runtime_future",
            "DROP FUNCTION public.trials_inflight_delta()",
            statement,
        ):
            with pytest.raises(psycopg.errors.InsufficientPrivilege):
                admin.execute(forbidden)
        admin.execute("RESET ROLE")


@pytest.mark.parametrize(
    "drift",
    [
        "membership",
        "runtime_login",
        "schema_owner",
        "stale_snapshot",
        "residual_trigger",
        "column_references",
        "version_writer",
    ],
)
def test_runtime_grant_refusal_preserves_existing_acl(
    application_migration_roles: tuple[Config, str, str, str],  # noqa: F811
    drift: str,
) -> None:
    cfg, url, owner, migrator = application_migration_roles
    command.upgrade(cfg, "head")
    runtime = owner + "_peer"
    with psycopg.connect(
        url.replace("postgresql+psycopg://", "postgresql://", 1), autocommit=True
    ) as admin:
        admin.execute(
            psycopg.sql.SQL(
                "ALTER ROLE {} NOLOGIN NOINHERIT; REVOKE {} FROM {}; "
                "ALTER ROLE {} NOLOGIN PASSWORD NULL; ALTER SCHEMA public OWNER TO {}"
            ).format(
                *(
                    psycopg.sql.Identifier(role)
                    for role in (runtime, owner, migrator, migrator, owner)
                )
            )
        )
        if drift == "membership":
            admin.execute(
                psycopg.sql.SQL("GRANT {} TO {}").format(
                    psycopg.sql.Identifier(owner), psycopg.sql.Identifier(runtime)
                )
            )
        elif drift == "runtime_login":
            admin.execute(
                psycopg.sql.SQL("ALTER ROLE {} LOGIN").format(psycopg.sql.Identifier(runtime))
            )
        elif drift == "schema_owner":
            admin.execute("ALTER SCHEMA public OWNER TO pg_database_owner")
        elif drift == "residual_trigger":
            admin.execute(
                psycopg.sql.SQL("GRANT TRIGGER ON public.trials TO {}").format(
                    psycopg.sql.Identifier(runtime)
                )
            )
        elif drift in {"column_references", "version_writer"}:
            grant = (
                "GRANT REFERENCES(id) ON public.trials TO {}"
                if drift == "column_references"
                else "GRANT UPDATE(version_num) ON public.alembic_version TO {}"
            )
            admin.execute(psycopg.sql.SQL(grant).format(psycopg.sql.Identifier(runtime)))
        else:
            admin.execute("BEGIN ISOLATION LEVEL REPEATABLE READ")
        before = _acl_state(admin)
        with pytest.raises(
            psycopg.errors.ObjectNotInPrerequisiteState, match="application runtime grants"
        ):
            with admin.transaction():
                admin.execute(
                    application_runtime_grants_ddl(owner_role=owner, runtime_role=runtime)
                )
        assert _acl_state(admin) == before
        if drift == "stale_snapshot":
            admin.execute("ROLLBACK")
        if drift == "membership":
            admin.execute(
                psycopg.sql.SQL("REVOKE {} FROM {}").format(
                    psycopg.sql.Identifier(owner), psycopg.sql.Identifier(runtime)
                )
            )
