# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import Field, HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class ControlPlaneSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="LOOM_CP_", env_file=".env", extra="forbid",
    )

    admin_secret_file: Path | None = None
    bind_host: str = "0.0.0.0"
    bind_port: int = 8080
    claimed_without_start_expiry_sec: int = 3600
    db_max_overflow: int = 40
    db_pool_size: int = 20
    db_pool_timeout_sec: float = 30.0
    db_url: PostgresDsn
    db_url_pool: PostgresDsn | None = None
    dev_reload: bool = False
    llm_gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    log_level: LogLevel = "info"
    metrics_port: int = 9090
    minio_access_key: SecretStr
    minio_endpoint: str = "http://loom-minio:9000"
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    signed_url_expiry_sec: int = 3600
    slurm_worker_controller_allowed_nodes: str = ""
    slurm_worker_controller_command_timeout_seconds: float = 20.0
    slurm_worker_controller_enabled: bool = False
    slurm_worker_controller_env_file: str = ""
    slurm_worker_controller_environment: str = "development"
    slurm_worker_controller_max_jobs: int = 0
    slurm_worker_controller_min_queued_trials: int = 1
    slurm_worker_controller_partition: str = ""
    slurm_worker_controller_pending_job_cap: int = 1
    slurm_worker_controller_pool_name: str = "oldlab"
    slurm_worker_controller_repo_dir: str = ""
    slurm_worker_controller_requested_concurrency: int = 6
    slurm_worker_controller_requested_cpus: int = 12
    slurm_worker_controller_requested_memory_mib: int = 58000
    slurm_worker_controller_sacct_path: str = "sacct"
    slurm_worker_controller_sbatch_path: str = "sbatch"
    slurm_worker_controller_scancel_path: str = "scancel"
    slurm_worker_controller_squeue_path: str = "squeue"
    slurm_worker_controller_stale_after_seconds: int = 300
    slurm_worker_controller_time_limit: str = "7-00:00:00"
    stale_running_trial_grace_sec: float = 900.0
    stale_running_trial_reclaim_enabled: bool = True
    stale_running_trial_silence_sec: float = 900.0
    stale_running_trial_timeout_multiplier: float = 3.0
    step_jwt_signing_key: SecretStr
    storage_auth_kind: str = "static_keys"
    storage_backend: str = "minio"
    trial_retry_default_backoff_base_sec: float = 30.0
    trial_retry_default_backoff_jitter: float = 0.2
    trial_retry_default_backoff_max_sec: float = 600.0
    trial_retry_default_backoff_multiplier: float = 2.0
    trial_retry_default_max_attempts: int = 3
    trial_retry_default_retry_on: list[str] = ["gateway_error", "provider_transport_disconnect"]
    worker_heartbeat_expiry_sec: int = 120
    worker_reclaim_sweep_interval_sec: int = 30


ControlPlaneSettings.model_rebuild()
