# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class ControlPlaneSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="LOOM_CP_", env_file=".env", extra="forbid",
    )

    admin_secret_file: Path | None = None
    bind_host: str = "0.0.0.0"
    bind_port: int = 8080
    db_url: PostgresDsn
    dev_reload: bool = False
    llm_gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    log_level: LogLevel = "info"
    metrics_port: int = 9090
    minio_access_key: SecretStr
    minio_endpoint: str = "http://loom-minio:9000"
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    signed_url_expiry_sec: int = 3600
    step_jwt_signing_key: SecretStr
    worker_heartbeat_expiry_sec: int = 15
    worker_reclaim_sweep_interval_sec: int = 30


ControlPlaneSettings.model_rebuild()
