[alembic]
script_location = capacity_migrations
file_template = %%(rev)s_shadow_management_schema
prepend_sys_path = .
path_separator = os
sqlalchemy.url =

[loggers]
keys = root, alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
