import { useEffect, useMemo, useRef, useState } from "react";

import type { PipelineStageRunSummary } from "../../api/client";
import { Button } from "../Button";
import { StatusPill } from "../StatusPill";
import { useFixedVirtualRows } from "../../hooks/useFixedVirtualRows";
import { bytewiseCompare, PIPELINE_STAGE_STATE } from "../../lib/pipelinePresentation";

const PAGE_SIZE = 250;
const ROW_HEIGHT = 44;

function sortStages(stages: PipelineStageRunSummary[]): PipelineStageRunSummary[] { return [...stages].sort((a, b) => a.topological_level - b.topological_level || bytewiseCompare(a.node_key, b.node_key) || bytewiseCompare(a.shard_key, b.shard_key)); }
function Cell({ value }: { value: string }): JSX.Element { return <span title={value} aria-label={value} className="block truncate">{value}</span>; }

export default function PipelineStageList({ stages, selectedNodeKey, onOpen }: { stages: PipelineStageRunSummary[]; selectedNodeKey: string | null; onOpen: (stage: PipelineStageRunSummary) => void }): JSX.Element {
  const [node, setNode] = useState(selectedNodeKey ?? ""); const [state, setState] = useState(""); const [outcome, setOutcome] = useState(""); const [resource, setResource] = useState(""); const [page, setPage] = useState(1); const [focusIndex, setFocusIndex] = useState(0);
  useEffect(() => { setNode(selectedNodeKey ?? ""); setPage(1); }, [selectedNodeKey]);
  useEffect(() => { setPage(1); setFocusIndex(0); }, [node, outcome, resource, state]);
  const filtered = useMemo(() => sortStages(stages.filter((item) => (!node || item.node_key === node) && (!state || item.state === state) && (!outcome || item.domain_outcome === outcome) && (!resource || item.resource_class === resource))), [node, outcome, resource, stages, state]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const rows = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); const virtual = useFixedVirtualRows(rows.length, ROW_HEIGHT, 660, 12); const viewportRef = useRef<HTMLDivElement>(null); const isVirtual = rows.length > 200;
  const fields = (row: PipelineStageRunSummary): string[] => [String(row.topological_level), row.node_key, row.shard_key, PIPELINE_STAGE_STATE[row.state].label, row.domain_outcome ?? "—", row.resource_class, String(row.attempt_count), row.retry_allowed ? "Eligible" : row.retry_ineligible_reason ?? "Ineligible"];
  const keydown = (event: React.KeyboardEvent, index: number): void => { if (event.key === "Enter") onOpen(rows[index]); else if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); const next = Math.max(0, Math.min(rows.length - 1, index + (event.key === "ArrowDown" ? 1 : -1))); setFocusIndex(next); if (isVirtual && viewportRef.current) viewportRef.current.scrollTop = virtual.scrollToIndex(next); requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-stage-row="${next}"]`)?.focus()); } };
  const renderCells = (row: PipelineStageRunSummary) => fields(row).map((value, index) => <div key={index} role="cell" className="min-w-0 px-2 py-2"><Cell value={value} /></div>);
  return <div className="space-y-3">
    <div className="grid gap-2 md:grid-cols-4"><label className="text-xs">Node key<input value={node} onChange={(e) => setNode(e.target.value.normalize("NFC"))} className="mt-1 block w-full rounded border px-2 py-1" /></label><label className="text-xs">State<select value={state} onChange={(e) => setState(e.target.value)} className="mt-1 block w-full rounded border px-2 py-1"><option value="">Any</option>{Object.keys(PIPELINE_STAGE_STATE).map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs">Domain outcome<input value={outcome} onChange={(e) => setOutcome(e.target.value.normalize("NFC"))} className="mt-1 block w-full rounded border px-2 py-1" /></label><label className="text-xs">Resource class<select value={resource} onChange={(e) => setResource(e.target.value)} className="mt-1 block w-full rounded border px-2 py-1"><option value="">Any</option><option>controller</option><option>cpu</option><option>gpu</option></select></label></div>
    <p className="text-sm text-slate-600">Page {page} of {pageCount} · {filtered.length} StageRuns</p>
    {isVirtual ? <div ref={viewportRef} role="table" aria-rowcount={rows.length} className="h-[660px] overflow-auto border" onScroll={(e) => virtual.onScroll(e.currentTarget.scrollTop)}><div role="rowgroup" className="relative" style={{ height: virtual.totalHeight }}>{virtual.rows.map((virtualRow) => { const row = rows[virtualRow.index]; return <div key={row.id} data-stage-row={virtualRow.index} role="row" aria-rowindex={virtualRow.index + 1} tabIndex={focusIndex === virtualRow.index ? 0 : -1} onKeyDown={(e) => keydown(e, virtualRow.index)} onDoubleClick={() => onOpen(row)} className="absolute grid w-full grid-cols-8 border-b bg-white text-xs" style={{ height: virtualRow.size, transform: `translateY(${virtualRow.start}px)` }}>{renderCells(row)}</div>; })}</div></div> : <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{["Level", "Node", "Shard", "State", "Outcome", "Resource", "Attempts", "Retry"].map((label) => <th key={label} className="px-2 py-2 text-left text-xs uppercase text-slate-500">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter") onOpen(row); }} onClick={() => onOpen(row)} className="cursor-pointer border-t hover:bg-slate-50">{fields(row).map((value, index) => <td key={index} className="max-w-40 px-2 py-2">{index === 3 ? <StatusPill variant={PIPELINE_STAGE_STATE[row.state].variant}>{value}</StatusPill> : <Cell value={value} />}</td>)}</tr>)}</tbody></table></div>}
    <div className="flex justify-end gap-2"><Button size="sm" disabled={page === 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</Button><Button size="sm" disabled={page === pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))}>Next</Button></div>
  </div>;
}
