# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import Field, HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class LoomServiceSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="LOOM_SVC_", env_file=".env", extra="forbid",
    )

    admin_secret_file: Path | None = None
    artifacts_bucket: str = "artifacts"
    auth_csrf_cookie_name: str = "loom_csrf"
    auth_csrf_header_name: str = "X-Loom-CSRF"
    auth_login_challenge_ttl_sec: int = 900
    auth_return_login_token: bool = False
    auth_session_cookie_name: str = "loom_session"
    auth_session_ttl_sec: int = 604800
    batch_runner_batch_size: int = 50
    batch_runner_cp_token: SecretStr | None = None
    batch_runner_poll_interval_sec: int = 5
    batch_runner_submit_rate_per_sec: int = 100
    bind_host: str = "0.0.0.0"
    bind_port: int = 8090
    control_plane_url: HttpUrl = cast(HttpUrl, "http://loom-control-plane:8080")
    db_url: PostgresDsn
    dev_reload: bool = False
    gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    local_servers_json: str = "{}"
    log_level: LogLevel = "info"
    minio_access_key: SecretStr
    minio_endpoint: str = "http://loom-minio:9000"
    minio_public_endpoint: str | None = None
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    signed_url_expiry_sec: int = 3600
    storage_auth_kind: str = "static_keys"
    storage_backend: str = "minio"
    taskset_materializer_batch_size: int = 1
    taskset_materializer_claim_ttl_sec: int = 600
    taskset_materializer_poll_interval_sec: int = 5
    taskset_materializer_upstream_cache_root: Path = Path("/tmp/loom-taskset-upstream")
    team_registration_open: bool = False
    trajectories_bucket: str = "trajectories"


LoomServiceSettings.model_rebuild()
