# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import Field, HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class LoomServiceSettings(BaseSettings):
    model_config = SettingsConfigDict(
        dotenv_filtering="only_existing",
        env_prefix="LOOM_SVC_",
        env_file=".env",
        extra="forbid",
    )

    admin_secret_file: Path | None = None
    artifacts_bucket: str = "artifacts"
    auth_csrf_cookie_name: str = "loom_csrf"
    auth_csrf_header_name: str = "X-Loom-CSRF"
    auth_login_challenge_ttl_sec: int = 900
    auth_return_login_token: bool = False
    auth_session_cookie_name: str = "loom_session"
    auth_session_ttl_sec: int = 604800
    batch_budget_estimate_input_tokens_per_call: int = 1000000
    batch_budget_estimate_llm_calls_per_trial: int = 1
    batch_budget_estimate_output_tokens_per_call: int = 0
    batch_runner_batch_size: int = 50
    batch_runner_cp_token: SecretStr | None = None
    batch_runner_poll_interval_sec: int = 5
    batch_runner_submit_rate_per_sec: int = 100
    bind_host: str = "0.0.0.0"
    bind_port: int = 8090
    control_plane_url: HttpUrl = cast(HttpUrl, "http://loom-control-plane:8080")
    db_url: PostgresDsn
    db_url_pool: PostgresDsn | None = None
    dev_instance_candidate_sha: str = ""
    dev_instance_container_registry: str = ""
    dev_instance_control_plane_url_template: str = "http://loom-control-plane.{namespace}.svc.cluster.local:8080"
    dev_instance_database_admin_url: PostgresDsn | None = None
    dev_instance_deployment_generation: int = 1
    dev_instance_image_tag: str = ""
    dev_instance_ingress_cert_manager_cluster_issuer: str = "letsencrypt-prod"
    dev_instance_ingress_class_name: str = "nginx"
    dev_instance_kube_context: str = ""
    dev_instance_kubectl_path: Path = Path("/usr/local/bin/kubectl")
    dev_instance_policy_drain_timeout_sec: int = 900
    dev_instance_slurm_actuator_config_json: str = "{}"
    dev_instances_enabled: bool = False
    dev_reload: bool = False
    gateway_url: HttpUrl = cast(HttpUrl, "http://loom-llm-gateway:9100")
    huggingface_api_key: SecretStr | None = Field(default=None, validation_alias="HF_TOKEN")
    k8s_worker_enabled: bool = True
    local_servers_json: str = "{}"
    log_level: LogLevel = "info"
    minio_access_key: SecretStr
    minio_endpoint: str = "http://loom-minio:9000"
    minio_public_endpoint: str | None = None
    minio_region: str = "us-east-1"
    minio_secret_key: SecretStr
    personal_dev_acceptance_binding_json: str = "{}"
    personal_dev_acceptance_plan_sha256: str = ""
    personal_dev_activation_ack_max_age_sec: int = 300
    personal_dev_activation_key_id: str = "personal-dev-agent-v1"
    personal_dev_activation_public_key_file: Path | None = None
    personal_dev_activation_public_key_sha256: str = ""
    personal_dev_builder_docker_path: Path = Path("/usr/bin/docker")
    personal_dev_builder_enabled: bool = False
    personal_dev_builder_global_concurrency: int = 4
    personal_dev_builder_image: str = ""
    personal_dev_builder_lease_sec: int = 4200
    personal_dev_builder_max_artifact_bytes: int = 6442450944
    personal_dev_builder_max_image_archive_bytes: int = 2147483648
    personal_dev_builder_per_owner_concurrency: int = 1
    personal_dev_builder_poll_interval_sec: float = 2.0
    personal_dev_builder_publisher_identity: str = ""
    personal_dev_builder_registry_auth_file: Path = Path("/var/run/loom-personal-dev-registry/config.json")
    personal_dev_builder_registry_prefix: str = ""
    personal_dev_builder_runtime_class_name: str = "loom-personal-dev-builder"
    personal_dev_builder_scanner_cache_dir: Path = Path("/var/lib/loom-personal-dev-scanner")
    personal_dev_builder_scanner_cache_identity_sha256: str = ""
    personal_dev_builder_scanner_database_metadata_sha256: str = ""
    personal_dev_builder_scanner_identity: str = ""
    personal_dev_builder_scanner_java_database_metadata_sha256: str = ""
    personal_dev_builder_scanner_path: Path = Path("/usr/local/bin/trivy")
    personal_dev_builder_scanner_policy_sha256: str = ""
    personal_dev_builder_skopeo_path: Path = Path("/usr/bin/skopeo")
    personal_dev_candidate_gc_lease_sec: int = 900
    personal_dev_candidate_gc_poll_interval_sec: float = 30.0
    personal_dev_candidate_gc_retention_sec: int = 86400
    personal_dev_candidate_retained_bytes_limit: int = 3221225472
    personal_dev_candidate_retained_count_limit: int = 8
    personal_dev_capacity_agent_image: str = ""
    personal_dev_capacity_agent_max_attempts: int = 10000
    personal_dev_capacity_agent_poll_interval_sec: float = 5.0
    personal_dev_capacity_ca_file: Path = Path("/var/run/loom-personal-dev-capacity/ca.pem")
    personal_dev_capacity_certificate_file: Path = Path("/var/run/loom-personal-dev-capacity/certificate.pem")
    personal_dev_capacity_database_namespace: str = "loom-dev"
    personal_dev_capacity_database_pod_label: str = "loom-dev-postgres"
    personal_dev_capacity_database_pod_label_key: str = "app"
    personal_dev_capacity_database_port: int = 5432
    personal_dev_capacity_dns_namespace: str = "kube-system"
    personal_dev_capacity_dns_pod_label: str = "kube-dns"
    personal_dev_capacity_dns_pod_label_key: str = "k8s-app"
    personal_dev_capacity_dns_port: int = 53
    personal_dev_capacity_lifecycle_bearer_token_file: Path = Path("/var/run/loom-personal-dev-capacity/lifecycle-token")
    personal_dev_capacity_lifecycle_ca_file: Path = Path("/var/run/loom-personal-dev-capacity/lifecycle-ca.pem")
    personal_dev_capacity_lifecycle_certificate_file: Path = Path("/var/run/loom-personal-dev-capacity/lifecycle-certificate.pem")
    personal_dev_capacity_lifecycle_private_key_file: Path = Path("/var/run/loom-personal-dev-capacity/lifecycle-private-key.pem")
    personal_dev_capacity_manager_namespace: str = "loom-dev"
    personal_dev_capacity_manager_origin: str = "https://loom-capacity-manager.loom-dev.svc.cluster.local:8443"
    personal_dev_capacity_manager_pod_label: str = "loom-capacity-manager"
    personal_dev_capacity_manager_pod_label_key: str = "app.kubernetes.io/name"
    personal_dev_capacity_manager_port: int = 8443
    personal_dev_capacity_pool_capabilities_json: str = "[{\"capability_id\":\"oldlab-x86-none\",\"pool_id\":\"oldlab\",\"operating_system\":\"linux\",\"cpu_architecture\":\"x86_64\",\"gpu_vendor\":\"none\",\"network_policies\":[\"public\"]},{\"capability_id\":\"gb10-arm-none\",\"pool_id\":\"gb10\",\"operating_system\":\"linux\",\"cpu_architecture\":\"arm64\",\"gpu_vendor\":\"none\",\"network_policies\":[\"public\"]}]"
    personal_dev_capacity_private_key_file: Path = Path("/var/run/loom-personal-dev-capacity/private-key.pem")
    personal_dev_global_live_instance_limit: int = 16
    personal_dev_native_builder_agent_image: str = ""
    personal_dev_native_builder_agent_instance_id: str = ""
    personal_dev_native_builder_agent_key_id: str = ""
    personal_dev_native_builder_enabled: bool = False
    personal_dev_native_builder_freshness_sec: int = 60
    personal_dev_native_builder_max_concurrency: int = 2
    personal_dev_native_builder_poll_interval_sec: float = 1.0
    personal_dev_native_builder_protocol_version: int = 1
    personal_dev_native_builder_public_key_file: Path | None = None
    personal_dev_native_builder_public_key_sha256: str = ""
    personal_dev_native_builder_runtime_profile_sha256: str = ""
    personal_dev_operational_binding_json: str = "{}"
    personal_dev_operational_plan_sha256: str = ""
    personal_dev_per_owner_aggregate_max_slots: int = 16
    personal_dev_per_owner_aggregate_min_slots: int = 8
    personal_dev_per_owner_live_instance_limit: int = 2
    personal_dev_protocol_versions_json: str = "{}"
    personal_dev_reconciler_lease_sec: int = 1800
    personal_dev_reconciler_poll_interval_sec: float = 2.0
    personal_dev_runtime_mode: str = "shadow"
    personal_dev_source_max_archive_bytes: int = 402653184
    personal_dev_trusted_launcher_profile_sha256: str = ""
    pipeline_stage1_smoke_key_id: str = "pipeline-stage1-operator-v1"
    pipeline_stage1_smoke_public_key_file: Path | None = None
    pipeline_stage1_smoke_signature_max_age_sec: int = 300
    public_base_url: HttpUrl | None = None
    service_execution_runtime_profile_json: str = "{}"
    signed_url_expiry_sec: int = 3600
    stale_running_trial_grace_sec: float = 900.0
    stale_running_trial_reclaim_enabled: bool = True
    stale_running_trial_silence_sec: float = 900.0
    stale_running_trial_timeout_multiplier: float = 3.0
    storage_auth_kind: str = "static_keys"
    storage_backend: str = "minio"
    taskset_fence_canary_token: SecretStr | None = None
    taskset_gc_poll_interval_sec: int = 3600
    taskset_gc_retention_days: int = 7
    taskset_manifest_max_bytes: int = 1048576
    taskset_materializer_batch_size: int = 1
    taskset_materializer_claim_ttl_sec: int = 600
    taskset_materializer_poll_interval_sec: int = 5
    taskset_materializer_transform_cpu_limit_sec: int = 10
    taskset_materializer_transform_memory_limit_mb: int = 256
    taskset_materializer_transform_network_isolated: bool = False
    taskset_materializer_transform_wall_timeout_sec: int = 30
    taskset_materializer_transforms_enabled: bool = False
    taskset_materializer_upstream_cache_root: Path = Path("/tmp/loom-taskset-upstream")
    taskset_quota_max_bundle_bytes: int = 5368709120
    taskset_quota_max_count_per_team: int = 50
    taskset_quota_max_storage_bytes_per_team: int = 21474836480
    team_quota_max_attempts_ceiling_default: int = 3
    team_registration_open: bool = False
    trajectories_bucket: str = "trajectories"
    trial_retry_default_backoff_base_sec: float = 30.0
    trial_retry_default_backoff_jitter: float = 0.2
    trial_retry_default_backoff_max_sec: float = 600.0
    trial_retry_default_backoff_multiplier: float = 2.0
    trial_retry_default_max_attempts: int = 3
    trial_retry_default_retry_on: list[str] = ["gateway_error", "provider_transport_disconnect", "node_setup_health"]
    untrusted_workload_isolation: bool = False
    worker_heartbeat_expiry_sec: int = 120
    workload_trust_mode: str = "internal_trusted"


LoomServiceSettings.model_rebuild()
