"""Codegen: schema → `_generated.py` per service."""
from __future__ import annotations

from pathlib import Path

from loom_config.codegen import render_cluster_config_example, render_service_settings
from loom_config.loader import load_schema

_REPO_SCHEMA = Path("config/loom-schema.toml")


def test_renders_control_plane_with_all_field_kinds() -> None:
    schema = load_schema(_REPO_SCHEMA)
    src = render_service_settings(schema, "control-plane")
    assert "class ControlPlaneSettings(BaseSettings):" in src
    assert "step_jwt_signing_key: SecretStr" in src
    assert "admin_secret_file: Path | None = None" in src
    assert "bind_port: int = 8080" in src
    assert "AUTOGENERATED" in src


def test_renders_gateway_includes_optional_provider_keys() -> None:
    schema = load_schema(_REPO_SCHEMA)
    src = render_service_settings(schema, "llm-gateway")
    assert "anthropic_api_key: SecretStr | None = None" in src
    assert "openai_api_key: SecretStr | None = None" in src
    assert "bind_port: int = 9100" in src


def test_renders_worker_includes_optional_paths() -> None:
    schema = load_schema(_REPO_SCHEMA)
    src = render_service_settings(schema, "worker")
    assert "fixtures_root: Path | None = None" in src
    assert "benchmark_cache: Path | None = None" in src
    assert "docker_socket: Path = Path(\"/var/run/docker.sock\")" in src


def test_rendered_settings_compiles_and_matches_snapshot(tmp_path: Path) -> None:
    """Round-trip: render → exec → assert model_fields match the
    pre-#146 snapshot. This is the migration safety net."""
    import json
    schema = load_schema(_REPO_SCHEMA)
    snapshot_dir = Path("tests/loom_config/snapshots")
    for svc, key, cls_name in [
        ("control-plane", "control_plane", "ControlPlaneSettings"),
        ("llm-gateway", "llm_gateway", "GatewaySettings"),
        ("loom-service", "loom_service", "LoomServiceSettings"),
        ("worker", "worker", "WorkerSettings"),
    ]:
        src = render_service_settings(schema, svc)
        ns: dict = {}
        exec(compile(src, f"<{svc}>", "exec"), ns)
        cls = ns[cls_name]
        actual = {
            name: {
                "annotation": str(f.annotation),
                "default": repr(f.default),
                "required": f.is_required(),
            }
            for name, f in cls.model_fields.items()
        }
        expected = json.loads((snapshot_dir / f"{key}.json").read_text())
        assert actual == expected, (
            f"{svc}: codegen output drifts from pre-#146 snapshot. "
            f"Diff missing fields: {set(expected) - set(actual)}, "
            f"extra fields: {set(actual) - set(expected)}"
        )


def test_renders_cluster_config_example() -> None:
    schema = load_schema(_REPO_SCHEMA)
    out = render_cluster_config_example(schema)
    assert "image_tag = \"0.7\"" in out
    assert "ingress_host = \"loom.example.com\"" in out
    assert "ingress_class_name = \"nginx\"" in out
    assert "ingress_tls_secret_name = \"loom-tls\"" in out
    assert "ingress_cert_manager_cluster_issuer = \"\"" in out
    assert "provider_egress_allowlist = []" in out
    assert "[replicas]" in out
    assert "service = 2" in out
    assert "control_plane = 2" in out
