# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import Field, HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel


class GatewaySettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="LOOM_GW_", env_file=".env", extra="forbid",
    )

    admin_secret_file: Path | None = None
    anthropic_api_key: SecretStr | None = None
    bind_host: str = "0.0.0.0"
    bind_port: int = 9100
    db_url: PostgresDsn
    dev_reload: bool = False
    egress_proxy_url: str = ""
    google_api_key: SecretStr | None = None
    huggingface_api_key: SecretStr | None = None
    llm_retry_base_backoff_sec: float = 0.5
    llm_retry_budget_sec: float = 60.0
    llm_retry_jitter_sec: float = 0.25
    llm_retry_max_attempts: int = 5
    llm_retry_max_backoff_sec: float = 8.0
    log_level: LogLevel = "info"
    metrics_port: int = 9101
    openai_api_key: SecretStr | None = None
    rate_card_cache_ttl_sec: int = 300
    step_jwt_signing_key: SecretStr
    together_api_key: SecretStr | None = None
    upstream_timeout_sec: float = 120.0


GatewaySettings.model_rebuild()
