"""dry run grant protocol

Revision ID: capacity_0003
Revises: capacity_0002
Create Date: 2026-08-11 09:13:04.067871
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "capacity_0003"
down_revision: str | Sequence[str] | None = "capacity_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "capacity_commitment_profile_binding_check",
        "capacity_observed_commitments",
        type_="check",
    )
    op.alter_column(
        "capacity_observed_commitments",
        "profile_generation",
        existing_type=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "capacity_observed_commitments",
        "profile_digest",
        existing_type=sa.Text(),
        nullable=True,
    )
    op.create_check_constraint(
        "capacity_commitment_profile_binding_check",
        "capacity_observed_commitments",
        "(profile_generation IS NULL AND profile_digest IS NULL) OR "
        "(profile_generation > 0 AND profile_digest ~ '^[0-9a-f]{64}$')",
    )
    op.create_check_constraint(
        "capacity_commitment_attribution_check",
        "capacity_observed_commitments",
        "(subject_id IS NOT NULL AND subject_incarnation IS NOT NULL "
        "AND deployment_generation > 0 AND profile_id IS NOT NULL "
        "AND profile_generation > 0 AND profile_digest IS NOT NULL) OR "
        "(subject_id IS NULL AND subject_incarnation IS NULL "
        "AND deployment_generation IS NULL AND profile_id IS NULL "
        "AND profile_generation IS NULL AND profile_digest IS NULL "
        "AND shape_id IS NULL AND kind = 'physical' "
        "AND state IN ('unknown','quarantined'))",
    )
    op.drop_constraint(
        "capacity_authority_limits_check",
        "capacity_authority_state",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_authority_limits_check",
        "capacity_authority_state",
        "global_pending_slot_ceiling >= 0 AND global_pending_job_ceiling >= 0 "
        "AND global_submission_rate_ceiling BETWEEN 0 AND 9223372036854",
    )
    op.drop_constraint(
        "capacity_pool_limits_check",
        "capacity_pools",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_pool_limits_check",
        "capacity_pools",
        "max_slots >= 0 AND max_pending_slots >= 0 "
        "AND max_pending_jobs >= 0 "
        "AND submission_rate_per_minute BETWEEN 0 AND 9223372036854",
    )
    op.add_column(
        "capacity_account_policies",
        sa.Column(
            "submission_rate_per_minute",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "capacity_subjects",
        sa.Column(
            "submission_rate_per_minute",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        "capacity_account_limits_check",
        "capacity_account_policies",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_account_limits_check",
        "capacity_account_policies",
        "min_reservation_slots >= 0 AND max_slots >= min_reservation_slots "
        "AND max_surge_slots >= 0 AND max_pending_slots >= 0 "
        "AND max_pending_jobs >= 0 "
        "AND submission_rate_per_minute BETWEEN 0 AND 9223372036854 "
        "AND max_live_subjects > 0 AND max_builds >= 0 "
        "AND max_artifact_bytes >= 0",
    )
    op.drop_constraint(
        "capacity_subject_limits_check",
        "capacity_subjects",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_subject_limits_check",
        "capacity_subjects",
        "min_slots >= 0 AND max_slots >= min_slots "
        "AND rollout_surge_slots >= 0 AND max_pending_slots >= 0 "
        "AND max_pending_jobs >= 0 "
        "AND submission_rate_per_minute BETWEEN 0 AND 9223372036854",
    )
    op.create_table(
        "capacity_executors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("executor_id", sa.Text(), nullable=False),
        sa.Column("executor_incarnation", sa.UUID(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("authority_incarnation", sa.UUID(), nullable=False),
        sa.Column("registered_writer_epoch", sa.BigInteger(), nullable=False),
        sa.Column("signing_key_id", sa.Text(), nullable=False),
        sa.Column("signing_key_sha256", sa.Text(), nullable=False),
        sa.Column("local_authority_sha256", sa.Text(), nullable=False),
        sa.Column("registration_actor", sa.Text(), nullable=False),
        sa.Column("registration_idempotency_key", sa.UUID(), nullable=False),
        sa.Column("registration_digest", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'dry-run'"), nullable=False),
        sa.Column(
            "command_high_water", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_command_digest", sa.Text(), nullable=True),
        sa.Column(
            "heartbeat_high_water", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_heartbeat_digest", sa.Text(), nullable=True),
        sa.Column(
            "journal_high_water", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("journal_digest", sa.Text(), nullable=True),
        sa.Column(
            "inventory_high_water", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_inventory_digest", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_heartbeat_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "signing_key_sha256 ~ '^[0-9a-f]{64}$' AND local_authority_sha256 ~ '^[0-9a-f]{64}$' AND registration_digest ~ '^[0-9a-f]{64}$' AND ((command_high_water = 0 AND last_command_digest IS NULL) OR (command_high_water > 0 AND last_command_digest ~ '^[0-9a-f]{64}$')) AND ((heartbeat_high_water = 0 AND last_heartbeat_digest IS NULL) OR (heartbeat_high_water > 0 AND last_heartbeat_digest ~ '^[0-9a-f]{64}$')) AND ((journal_high_water = 0 AND (journal_digest IS NULL OR journal_digest = repeat('0', 64))) OR (journal_high_water > 0 AND journal_digest ~ '^[0-9a-f]{64}$' AND journal_digest <> repeat('0', 64))) AND ((inventory_high_water = 0 AND last_inventory_digest IS NULL) OR (inventory_high_water > 0 AND last_inventory_digest ~ '^[0-9a-f]{64}$'))",
            name="capacity_executor_digest_check",
        ),
        sa.CheckConstraint(
            "state IN ('dry-run','fenced','equivocal')", name="capacity_executor_state_check"
        ),
        sa.CheckConstraint(
            "pool_generation > 0 AND registered_writer_epoch > 0 AND command_high_water >= 0 AND heartbeat_high_water >= 0 AND journal_high_water >= 0 AND inventory_high_water >= 0",
            name="capacity_executor_epoch_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "executor_id",
            "executor_incarnation",
            "pool_id",
            "pool_generation",
            name="capacity_executor_exact_binding_key",
        ),
        sa.UniqueConstraint("executor_incarnation", name="capacity_executor_incarnation_key"),
        sa.UniqueConstraint(
            "id",
            "executor_incarnation",
            "pool_id",
            "pool_generation",
            name="capacity_executor_observation_binding_key",
        ),
        sa.UniqueConstraint(
            "registration_idempotency_key", name="capacity_executor_registration_idempotency_key"
        ),
    )
    op.create_index(
        "capacity_executor_one_current_per_pool_idx",
        "capacity_executors",
        ["pool_id"],
        unique=True,
        postgresql_where=sa.text("state = 'dry-run'"),
    )
    op.create_table(
        "capacity_executor_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("executor_row_id", sa.UUID(), nullable=False),
        sa.Column("executor_incarnation", sa.UUID(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("inventory_sequence", sa.BigInteger(), nullable=False),
        sa.Column("inventory_digest", sa.Text(), nullable=False),
        sa.Column("journal_sequence", sa.BigInteger(), nullable=False),
        sa.Column("journal_digest", sa.Text(), nullable=False),
        sa.Column("authenticated_count", sa.BigInteger(), nullable=False),
        sa.Column("quarantined_count", sa.BigInteger(), nullable=False),
        sa.Column("foreign_count", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "classification_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("validity", sa.Text(), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "database_received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "authenticated_count >= 0 AND quarantined_count >= 0 AND foreign_count >= 0",
            name="capacity_executor_observation_count_check",
        ),
        sa.CheckConstraint(
            "inventory_digest ~ '^[0-9a-f]{64}$' AND journal_digest ~ '^[0-9a-f]{64}$'",
            name="capacity_executor_observation_digest_check",
        ),
        sa.CheckConstraint(
            "executable = false", name="capacity_executor_observation_dry_run_only_check"
        ),
        sa.CheckConstraint(
            "inventory_sequence > 0 AND journal_sequence >= 0",
            name="capacity_executor_observation_sequence_check",
        ),
        sa.CheckConstraint(
            "validity IN ('valid','quarantined')",
            name="capacity_executor_observation_validity_check",
        ),
        sa.ForeignKeyConstraint(
            ["executor_row_id", "executor_incarnation", "pool_id", "pool_generation"],
            [
                "capacity_executors.id",
                "capacity_executors.executor_incarnation",
                "capacity_executors.pool_id",
                "capacity_executors.pool_generation",
            ],
            name="capacity_executor_observation_binding_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "executor_incarnation",
            "inventory_sequence",
            name="capacity_executor_observation_sequence_key",
        ),
    )
    op.create_table(
        "capacity_launch_rate_buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("scope_identity", sa.Text(), nullable=False),
        sa.Column("rate_per_minute", sa.BigInteger(), nullable=False),
        sa.Column("capacity_microtokens", sa.BigInteger(), nullable=False),
        sa.Column("available_microtokens", sa.BigInteger(), nullable=False),
        sa.Column("refill_remainder", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_refill_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'dry-run'"), nullable=False),
        sa.CheckConstraint(
            "scope IN ('global','account','subject','pool')",
            name="capacity_launch_rate_bucket_scope_check",
        ),
        sa.CheckConstraint(
            "state = 'dry-run'", name="capacity_launch_rate_bucket_dry_run_only_check"
        ),
        sa.CheckConstraint(
            "configuration_epoch > 0 AND rate_per_minute BETWEEN 0 AND 9223372036854 AND capacity_microtokens = rate_per_minute * 1000000 AND available_microtokens >= 0 AND available_microtokens <= capacity_microtokens AND refill_remainder >= 0 AND refill_remainder < 60",
            name="capacity_launch_rate_bucket_quantity_check",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "configuration_epoch",
            "scope",
            "scope_identity",
            name="capacity_launch_rate_bucket_scope_key",
        ),
    )
    op.create_table(
        "capacity_reservation_tranches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("authority_incarnation", sa.UUID(), nullable=False),
        sa.Column("writer_epoch", sa.BigInteger(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("executor_id", sa.Text(), nullable=False),
        sa.Column("executor_incarnation", sa.UUID(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("tier_id", sa.Text(), nullable=False),
        sa.Column("candidate_generation", sa.BigInteger(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("proposal_digest", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'proposed'"), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("accepted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state <> 'closed' AND closure_reason IS NULL) OR (state = 'closed' AND closure_reason IN ('proposal-expired','proposal-superseded','fully-released'))",
            name="capacity_reservation_tranche_closure_check",
        ),
        sa.CheckConstraint(
            "(state = 'proposed' AND accepted_at IS NULL AND closed_at IS NULL) OR (state = 'accepted' AND accepted_at IS NOT NULL AND closed_at IS NULL) OR (state = 'closed' AND closed_at IS NOT NULL)",
            name="capacity_reservation_tranche_state_time_check",
        ),
        sa.CheckConstraint(
            "proposal_digest ~ '^[0-9a-f]{64}$'", name="capacity_reservation_tranche_digest_check"
        ),
        sa.CheckConstraint(
            "state IN ('proposed','accepted','closed')",
            name="capacity_reservation_tranche_state_check",
        ),
        sa.CheckConstraint(
            "tier_id IN ('production','staging','development')",
            name="capacity_reservation_tranche_tier_check",
        ),
        sa.CheckConstraint(
            "executable = false", name="capacity_reservation_tranche_dry_run_only_check"
        ),
        sa.CheckConstraint(
            "writer_epoch > 0 AND configuration_epoch > 0 AND allocation_epoch > 0 AND pool_generation > 0 AND deployment_generation > 0 AND candidate_generation > 0",
            name="capacity_reservation_tranche_epoch_check",
        ),
        sa.ForeignKeyConstraint(
            ["allocation_epoch"],
            ["capacity_allocation_epochs.allocation_epoch"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["executor_id", "executor_incarnation", "pool_id", "pool_generation"],
            [
                "capacity_executors.executor_id",
                "capacity_executors.executor_incarnation",
                "capacity_executors.pool_id",
                "capacity_executors.pool_generation",
            ],
            name="capacity_reservation_tranche_executor_binding_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="capacity_reservation_tranche_idempotency_key"),
    )
    op.create_table(
        "capacity_reservation_release_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tranche_id", sa.UUID(), nullable=False),
        sa.Column("shape_instance_id", sa.Text(), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("executor_id", sa.Text(), nullable=False),
        sa.Column("executor_incarnation", sa.UUID(), nullable=False),
        sa.Column("command_sequence", sa.BigInteger(), nullable=False),
        sa.Column("inventory_sequence", sa.BigInteger(), nullable=False),
        sa.Column("terminal_kind", sa.Text(), nullable=False),
        sa.Column("terminal_identity", sa.Text(), nullable=False),
        sa.Column("terminal_evidence_sha256", sa.Text(), nullable=False),
        sa.Column("protected_registration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("bootstrap_revoked", sa.Boolean(), nullable=False),
        sa.Column("protected_release_sha256", sa.Text(), nullable=False),
        sa.Column("evidence_digest", sa.Text(), nullable=False),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_digest ~ '^[0-9a-f]{64}$' AND terminal_evidence_sha256 ~ '^[0-9a-f]{64}$' AND protected_release_sha256 ~ '^[0-9a-f]{64}$'",
            name="capacity_reservation_release_digest_check",
        ),
        sa.CheckConstraint(
            "terminal_kind IN ('unused','slurm-job','worker')",
            name="capacity_reservation_release_kind_check",
        ),
        sa.CheckConstraint(
            "command_sequence > 0 AND inventory_sequence > 0 AND protected_registration_epoch > 0 AND bootstrap_revoked = true",
            name="capacity_reservation_release_sequence_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "executor_incarnation",
            "terminal_kind",
            "terminal_identity",
            name="capacity_reservation_release_terminal_key",
        ),
        sa.UniqueConstraint("shape_instance_id", name="capacity_reservation_release_shape_key"),
    )
    op.create_table(
        "capacity_reservation_shapes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tranche_id", sa.UUID(), nullable=False),
        sa.Column("shape_instance_id", sa.Text(), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("shape_id", sa.Text(), nullable=False),
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("profile_generation", sa.BigInteger(), nullable=False),
        sa.Column("profile_digest", sa.Text(), nullable=False),
        sa.Column("concurrency_slots", sa.BigInteger(), nullable=False),
        sa.Column("resource_vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("node_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "rollout_surge_slots", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("old_shape_backing_id", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'proposed'"), nullable=False),
        sa.Column("release_evidence_digest", sa.Text(), nullable=True),
        sa.Column("released_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'released' AND release_evidence_digest IS NOT NULL AND released_at IS NOT NULL) OR (state <> 'released' AND release_evidence_digest IS NULL AND released_at IS NULL)",
            name="capacity_reservation_shape_release_check",
        ),
        sa.CheckConstraint(
            "profile_digest ~ '^[0-9a-f]{64}$'", name="capacity_reservation_shape_digest_check"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(resource_vector -> 'slots') = 'number' AND (resource_vector ->> 'slots')::bigint = concurrency_slots AND jsonb_typeof(node_ids) = 'array' AND jsonb_array_length(node_ids) > 0",
            name="capacity_reservation_shape_binding_check",
        ),
        sa.CheckConstraint(
            "state IN ('proposed','accepted','releasing','released')",
            name="capacity_reservation_shape_state_check",
        ),
        sa.CheckConstraint(
            "(rollout_surge_slots = 0 AND old_shape_backing_id IS NULL) OR (rollout_surge_slots > 0 AND old_shape_backing_id IS NOT NULL)",
            name="capacity_reservation_shape_surge_check",
        ),
        sa.CheckConstraint(
            "profile_generation > 0 AND concurrency_slots > 0 AND rollout_surge_slots >= 0 AND rollout_surge_slots <= concurrency_slots",
            name="capacity_reservation_shape_quantity_check",
        ),
        sa.ForeignKeyConstraint(
            ["tranche_id"], ["capacity_reservation_tranches.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intent_id", name="capacity_reservation_shape_intent_key"),
        sa.UniqueConstraint("shape_instance_id", name="capacity_reservation_shape_identity_key"),
        sa.UniqueConstraint(
            "tranche_id",
            "shape_instance_id",
            "intent_id",
            name="capacity_reservation_shape_exact_binding_key",
        ),
    )
    op.create_table(
        "capacity_submission_intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tranche_id", sa.UUID(), nullable=False),
        sa.Column("shape_instance_id", sa.Text(), nullable=False),
        sa.Column("executor_id", sa.Text(), nullable=False),
        sa.Column("executor_incarnation", sa.UUID(), nullable=False),
        sa.Column("ownership_metadata_sha256", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'prepared'"), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("bootstrap_registration_epoch", sa.BigInteger(), nullable=True),
        sa.Column("bootstrap_evidence_sha256", sa.Text(), nullable=True),
        sa.Column("launch_ready_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((bootstrap_registration_epoch IS NULL AND bootstrap_evidence_sha256 IS NULL AND launch_ready_at IS NULL) OR (bootstrap_registration_epoch > 0 AND bootstrap_evidence_sha256 ~ '^[0-9a-f]{64}$' AND launch_ready_at IS NOT NULL)) AND (state <> 'launch-ready' OR bootstrap_registration_epoch IS NOT NULL) AND (state <> 'prepared' OR bootstrap_registration_epoch IS NULL) AND (state NOT IN ('submitting-unknown','bound','observed','terminal') OR bootstrap_registration_epoch IS NOT NULL)",
            name="capacity_submission_intent_bootstrap_check",
        ),
        sa.CheckConstraint(
            "ownership_metadata_sha256 ~ '^[0-9a-f]{64}$'",
            name="capacity_submission_intent_digest_check",
        ),
        sa.CheckConstraint(
            "state IN ('prepared','launch-ready','submitting-unknown','bound','observed','terminal','closing','closed','quarantined')",
            name="capacity_submission_intent_state_check",
        ),
        sa.CheckConstraint(
            "executable = false", name="capacity_submission_intent_dry_run_only_check"
        ),
        sa.ForeignKeyConstraint(
            ["tranche_id", "shape_instance_id", "id"],
            [
                "capacity_reservation_shapes.tranche_id",
                "capacity_reservation_shapes.shape_instance_id",
                "capacity_reservation_shapes.intent_id",
            ],
            name="capacity_submission_intent_shape_binding_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "executor_id",
            "executor_incarnation",
            name="capacity_submission_intent_executor_binding_key",
        ),
        sa.UniqueConstraint("shape_instance_id", name="capacity_submission_intent_shape_key"),
    )
    op.create_table(
        "capacity_launch_permits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("permit_epoch", sa.BigInteger(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("executor_id", sa.Text(), nullable=False),
        sa.Column("executor_incarnation", sa.UUID(), nullable=False),
        sa.Column("launch_rank", sa.BigInteger(), nullable=False),
        sa.Column("permit_digest", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'current'"), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("dry_run_consumed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'consumed' AND dry_run_consumed_at IS NOT NULL) OR (state <> 'consumed' AND dry_run_consumed_at IS NULL)",
            name="capacity_launch_permit_consumption_check",
        ),
        sa.CheckConstraint(
            "permit_digest ~ '^[0-9a-f]{64}$'", name="capacity_launch_permit_digest_check"
        ),
        sa.CheckConstraint(
            "state IN ('current','superseded','consumed','revoked')",
            name="capacity_launch_permit_state_check",
        ),
        sa.CheckConstraint("executable = false", name="capacity_launch_permit_dry_run_only_check"),
        sa.CheckConstraint(
            "permit_epoch > 0 AND allocation_epoch > 0 AND configuration_epoch > 0 AND launch_rank > 0",
            name="capacity_launch_permit_epoch_check",
        ),
        sa.ForeignKeyConstraint(
            ["allocation_epoch"],
            ["capacity_allocation_epochs.allocation_epoch"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["intent_id", "executor_id", "executor_incarnation"],
            [
                "capacity_submission_intents.id",
                "capacity_submission_intents.executor_id",
                "capacity_submission_intents.executor_incarnation",
            ],
            name="capacity_launch_permit_intent_binding_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="capacity_launch_permit_idempotency_key"),
        sa.UniqueConstraint("intent_id", "permit_epoch", name="capacity_launch_permit_epoch_key"),
    )
    op.create_index(
        "capacity_launch_permit_one_current_per_intent_idx",
        "capacity_launch_permits",
        ["intent_id"],
        unique=True,
        postgresql_where=sa.text("state = 'current'"),
    )
    op.create_table(
        "capacity_protected_release_acknowledgements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("authority_incarnation", sa.UUID(), nullable=False),
        sa.Column("writer_epoch", sa.BigInteger(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("tranche_id", sa.UUID(), nullable=False),
        sa.Column("shape_instance_id", sa.Text(), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("reporter_incarnation", sa.UUID(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("bootstrap_registration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("protected_registration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("bootstrap_revoked", sa.Boolean(), nullable=False),
        sa.Column("protected_release_sha256", sa.Text(), nullable=False),
        sa.Column("acknowledgement_digest", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "protected_release_sha256 ~ '^[0-9a-f]{64}$' AND acknowledgement_digest ~ '^[0-9a-f]{64}$'",
            name="capacity_protected_release_digest_check",
        ),
        sa.CheckConstraint(
            "executable = false", name="capacity_protected_release_dry_run_only_check"
        ),
        sa.CheckConstraint(
            "writer_epoch > 0 AND configuration_epoch > 0 AND allocation_epoch > 0 AND deployment_generation > 0 AND pool_generation > 0 AND bootstrap_registration_epoch >= 0 AND protected_registration_epoch > bootstrap_registration_epoch AND bootstrap_revoked = true",
            name="capacity_protected_release_epoch_check",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "subject_incarnation", "reporter_incarnation"],
            [
                "capacity_demand_reporters.subject_id",
                "capacity_demand_reporters.subject_incarnation",
                "capacity_demand_reporters.reporter_incarnation",
            ],
            name="capacity_protected_release_reporter_binding_fkey",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tranche_id", "shape_instance_id", "intent_id"],
            [
                "capacity_reservation_shapes.tranche_id",
                "capacity_reservation_shapes.shape_instance_id",
                "capacity_reservation_shapes.intent_id",
            ],
            name="capacity_protected_release_shape_binding_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="capacity_protected_release_idempotency_key"),
        sa.UniqueConstraint("shape_instance_id", name="capacity_protected_release_shape_key"),
    )
    op.create_foreign_key(
        "capacity_allocation_configuration_epoch_fkey",
        "capacity_allocation_epochs",
        "capacity_configuration_epochs",
        ["configuration_epoch"],
        ["configuration_epoch"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "capacity_release_evidence_shape_binding_fkey",
        "capacity_reservation_release_evidence",
        "capacity_reservation_shapes",
        ["tranche_id", "shape_instance_id", "intent_id"],
        ["tranche_id", "shape_instance_id", "intent_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "capacity_release_evidence_intent_binding_fkey",
        "capacity_reservation_release_evidence",
        "capacity_submission_intents",
        ["intent_id", "executor_id", "executor_incarnation"],
        ["id", "executor_id", "executor_incarnation"],
        ondelete="RESTRICT",
    )
    op.execute(
        """
        CREATE FUNCTION capacity_reject_release_evidence_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog
        AS $$
        BEGIN
            RAISE EXCEPTION
                'capacity reservation release evidence is append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER capacity_protected_release_append_only
        BEFORE UPDATE OR DELETE ON capacity_protected_release_acknowledgements
        FOR EACH ROW
        EXECUTE FUNCTION capacity_reject_release_evidence_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER capacity_release_evidence_append_only
        BEFORE UPDATE OR DELETE ON capacity_reservation_release_evidence
        FOR EACH ROW
        EXECUTE FUNCTION capacity_reject_release_evidence_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER capacity_protected_release_append_only_truncate
        BEFORE TRUNCATE ON capacity_protected_release_acknowledgements
        FOR EACH STATEMENT
        EXECUTE FUNCTION capacity_reject_release_evidence_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER capacity_release_evidence_append_only_truncate
        BEFORE TRUNCATE ON capacity_reservation_release_evidence
        FOR EACH STATEMENT
        EXECUTE FUNCTION capacity_reject_release_evidence_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER capacity_release_evidence_append_only_truncate "
        "ON capacity_reservation_release_evidence"
    )
    op.execute(
        "DROP TRIGGER capacity_protected_release_append_only_truncate "
        "ON capacity_protected_release_acknowledgements"
    )
    op.execute(
        "DROP TRIGGER capacity_release_evidence_append_only "
        "ON capacity_reservation_release_evidence"
    )
    op.execute(
        "DROP TRIGGER capacity_protected_release_append_only "
        "ON capacity_protected_release_acknowledgements"
    )
    op.execute("DROP FUNCTION capacity_reject_release_evidence_mutation()")
    op.drop_constraint(
        "capacity_allocation_configuration_epoch_fkey",
        "capacity_allocation_epochs",
        type_="foreignkey",
    )
    op.drop_index(
        "capacity_launch_permit_one_current_per_intent_idx",
        table_name="capacity_launch_permits",
        postgresql_where=sa.text("state = 'current'"),
    )
    op.drop_table("capacity_launch_permits")
    op.drop_table("capacity_protected_release_acknowledgements")
    op.drop_table("capacity_reservation_release_evidence")
    op.drop_table("capacity_submission_intents")
    op.drop_table("capacity_reservation_shapes")
    op.drop_table("capacity_reservation_tranches")
    op.drop_table("capacity_launch_rate_buckets")
    op.drop_table("capacity_executor_observations")
    op.drop_index(
        "capacity_executor_one_current_per_pool_idx",
        table_name="capacity_executors",
        postgresql_where=sa.text("state = 'dry-run'"),
    )
    op.drop_table("capacity_executors")
    op.drop_constraint(
        "capacity_commitment_attribution_check",
        "capacity_observed_commitments",
        type_="check",
    )
    op.drop_constraint(
        "capacity_commitment_profile_binding_check",
        "capacity_observed_commitments",
        type_="check",
    )
    op.execute(
        "DELETE FROM capacity_observed_commitments "
        "WHERE profile_generation IS NULL OR profile_digest IS NULL"
    )
    op.alter_column(
        "capacity_observed_commitments",
        "profile_digest",
        existing_type=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "capacity_observed_commitments",
        "profile_generation",
        existing_type=sa.BigInteger(),
        nullable=False,
    )
    op.create_check_constraint(
        "capacity_commitment_profile_binding_check",
        "capacity_observed_commitments",
        "profile_generation > 0 AND profile_digest ~ '^[0-9a-f]{64}$'",
    )
    op.drop_constraint(
        "capacity_subject_limits_check",
        "capacity_subjects",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_subject_limits_check",
        "capacity_subjects",
        "min_slots >= 0 AND max_slots >= min_slots "
        "AND rollout_surge_slots >= 0 AND max_pending_slots >= 0 "
        "AND max_pending_jobs >= 0",
    )
    op.drop_constraint(
        "capacity_account_limits_check",
        "capacity_account_policies",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_account_limits_check",
        "capacity_account_policies",
        "min_reservation_slots >= 0 AND max_slots >= min_reservation_slots "
        "AND max_surge_slots >= 0 AND max_pending_slots >= 0 "
        "AND max_pending_jobs >= 0 AND max_live_subjects > 0 "
        "AND max_builds >= 0 AND max_artifact_bytes >= 0",
    )
    op.drop_column("capacity_subjects", "submission_rate_per_minute")
    op.drop_column("capacity_account_policies", "submission_rate_per_minute")
    op.drop_constraint(
        "capacity_pool_limits_check",
        "capacity_pools",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_pool_limits_check",
        "capacity_pools",
        "max_slots >= 0 AND max_pending_slots >= 0 "
        "AND max_pending_jobs >= 0 AND submission_rate_per_minute >= 0",
    )
    op.drop_constraint(
        "capacity_authority_limits_check",
        "capacity_authority_state",
        type_="check",
    )
    op.create_check_constraint(
        "capacity_authority_limits_check",
        "capacity_authority_state",
        "global_pending_slot_ceiling >= 0 AND global_pending_job_ceiling >= 0 "
        "AND global_submission_rate_ceiling >= 0",
    )
    # ### end Alembic commands ###
