binary_name = "/opt/loom/gvisor/release-20260810.0/runsc"

[runsc_config]
  allow-flag-override = "false"
  allow-packet-socket-write = "false"
  allow-suid = "false"
  debug = "false"
  directfs = "false"
  file-access = "exclusive"
  file-access-mounts = "shared"
  gvisor-marker-file = "true"
  host-fifo = "none"
  host-settings = "check"
  host-uds = "none"
  ignore-cgroups = "false"
  mount-cgroup-v2 = "true"
  net-raw = "false"
  network = "sandbox"
  oci-seccomp = "true"
  platform = "kvm"
  platform_device_path = "/dev/kvm"
  profile = "false"
  restore-spec-validation = "enforce"
  rootless = "false"
  sidecar-release-enforcement-policy = "ALWAYS"
  strace = "false"
  systemd-cgroup = "true"
  watchdog-action = "panic"
