"""Schema-driven codegen.

Produces:
- `src/loom_*/config/_generated.py` — one Pydantic BaseSettings per service.
- `config/cluster-config.example.toml` — operator starter file from render_config defaults.

Invoked by `loom config codegen` and `loom config codegen --check` (CI).
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from loom_config.loader import (
    RenderConfigEntry,
    Schema,
    ServiceConfigEntry,
    load_schema,
)

_HEADER = """\
# ruff: noqa
# AUTOGENERATED — do not edit. Regenerate with `loom config codegen`.
# Source of truth: config/loom-schema.toml. Editing this file directly
# will be reverted by CI's `loom config codegen --check` gate.

from pathlib import Path
from typing import cast

from pydantic import Field, HttpUrl, PostgresDsn, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from loom.models.types import LogLevel
"""

_SERVICE_META = {
    "control-plane": ("ControlPlaneSettings", "CP"),
    "llm-gateway":   ("GatewaySettings",      "GW"),
    "loom-service":  ("LoomServiceSettings",  "SVC"),
    "worker":        ("WorkerSettings",       "WORKER"),
}

_PKG_NAME = {
    "control-plane": "loom_control_plane",
    "llm-gateway":   "loom_llm_gateway",
    "loom-service":  "loom_service",
    "worker":        "loom_worker",
}


def _format_default(entry: ServiceConfigEntry, service: str, py: str) -> str:
    """4-rule precedence per spec §Codegen rules."""
    if entry.required:
        return "<required>"
    if entry.default_per_service is not None and service in entry.default_per_service:
        return _literal(entry.default_per_service[service], py)
    if entry.default is not None:
        return _literal(entry.default, py)
    return "<optional>"


def _literal(value: Any, py: str) -> str:
    if py == "Path":
        return f'Path("{value}")'
    if py in ("str", "LogLevel", "HttpUrl", "PostgresDsn"):
        return f'"{value}"'
    if py == "bool":
        return "True" if value else "False"
    if py in ("int", "float"):
        return repr(value)
    if py == "str_list":
        if value is None:
            return "[]"
        if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
            raise ValueError(f"expected list[str] default, got {value!r}")
        return json.dumps(value)
    raise ValueError(f"don't know how to literal {py} value {value!r}")


def _field_line(entry: ServiceConfigEntry, service: str) -> str:
    py = entry.python_type
    if py == "table":
        raise ValueError(
            f"service_config.{entry.name}: python_type='table' is only "
            f"valid in render_config"
        )
    rendered_default = _format_default(entry, service, py)
    annotation = "list[str]" if py == "str_list" else py
    alias = (
        entry.env_var_for(service)
        if entry.env_override and service in entry.env_override
        else None
    )
    if alias is not None:
        if rendered_default == "<required>":
            return (
                f"    {entry.name}: {annotation} = "
                f"Field(validation_alias=\"{alias}\")"
            )
        if rendered_default == "<optional>":
            return (
                f"    {entry.name}: {annotation} | None = "
                f"Field(default=None, validation_alias=\"{alias}\")"
            )
        if py in ("HttpUrl", "PostgresDsn"):
            # Empty-string default for a URL type cannot be validated by pydantic;
            # treat it as Optional with None default instead (#609).
            if rendered_default == '""':
                return (
                    f"    {entry.name}: {annotation} | None = "
                    f"Field(default=None, validation_alias=\"{alias}\")"
                )
            default_expr = f"cast({py}, {rendered_default})"
        else:
            default_expr = rendered_default
        return (
            f"    {entry.name}: {annotation} = "
            f"Field(default={default_expr}, validation_alias=\"{alias}\")"
        )
    if rendered_default == "<required>":
        return f"    {entry.name}: {annotation}"
    if rendered_default == "<optional>":
        return f"    {entry.name}: {annotation} | None = None"
    if py == "str_list":
        return f"    {entry.name}: list[str] = {rendered_default}"
    if py in ("HttpUrl", "PostgresDsn"):
        # Empty-string default for a URL type cannot be validated by pydantic;
        # treat it as Optional with None default instead (#609).
        if rendered_default == '""':
            return f"    {entry.name}: {py} | None = None"
        return f"    {entry.name}: {py} = cast({py}, {rendered_default})"
    return f"    {entry.name}: {py} = {rendered_default}"


def render_service_settings(schema: Schema, service: str) -> str:
    cls_name, prefix = _SERVICE_META[service]
    body_lines = [_field_line(e, service) for e in schema.service_config_for(service)]
    body = "\n".join(body_lines) if body_lines else "    pass"
    return (
        _HEADER
        + "\n\n"
        + f"class {cls_name}(BaseSettings):\n"
        + "    model_config = SettingsConfigDict(\n"
        + f"        env_prefix=\"LOOM_{prefix}_\", env_file=\".env\", extra=\"forbid\",\n"
        + "    )\n\n"
        + body
        + "\n\n\n"
        + f"{cls_name}.model_rebuild()\n"
    )


def _render_render_value(entry: RenderConfigEntry) -> str:
    py = entry.python_type
    if py == "table":
        assert entry.fields is not None
        sub = "\n".join(
            f"{k} = {_toml_literal(v, _guess_py(v))}"
            for k, v in entry.fields.items()
        )
        return f"\n[{entry.name}]\n{sub}\n"
    return f"{entry.name} = {_toml_literal(entry.default, py)}\n"


def _toml_literal(value: Any, py: str) -> str:
    """TOML-cased literal for cluster-config.example.toml output.

    Diverges from `_literal` only in that TOML requires lowercase
    `true`/`false` where Python source uses `True`/`False`.
    """
    if py == "bool":
        return "true" if value else "false"
    return _literal(value, py)


def _guess_py(value: Any) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, list):
        return "str_list"
    return "str"


def render_cluster_config_example(schema: Schema) -> str:
    head = (
        "# AUTOGENERATED — do not edit by hand. Regenerate with `loom config codegen`.\n"
        "# Operator-tunable knobs for `loom cluster render --config <FILE>`.\n"
        "# Each value below is the default; uncomment + edit to override.\n"
        "\n"
    )
    scalar_chunks: list[str] = []
    table_chunks: list[str] = []
    for name in sorted(schema.render_config):
        entry = schema.render_config[name]
        block = _render_render_value(entry)
        if entry.description:
            block = f"# {entry.description}\n" + block
        if entry.python_type == "table":
            table_chunks.append(block)
        else:
            scalar_chunks.append(block)
    return head + "".join(scalar_chunks) + "".join(table_chunks)


@dataclass(frozen=True)
class CodegenResult:
    path: Path
    content: str


def codegen_all(schema: Schema, repo_root: Path) -> list[CodegenResult]:
    out: list[CodegenResult] = []
    for service in _SERVICE_META:
        pkg = _PKG_NAME[service]
        out.append(CodegenResult(
            path=repo_root / "src" / pkg / "config" / "_generated.py",
            content=render_service_settings(schema, service),
        ))
    out.append(CodegenResult(
        path=repo_root / "config" / "cluster-config.example.toml",
        content=render_cluster_config_example(schema),
    ))
    return out


def main(argv: list[str] | None = None) -> int:
    """`loom config codegen [--check]` entry point."""
    import argparse
    import sys
    parser = argparse.ArgumentParser(prog="loom config codegen")
    parser.add_argument("--check", action="store_true",
        help="Exit 1 if any committed artifact drifts from schema.")
    parser.add_argument("--repo-root", default=".",
        help="Repo root (default: cwd).")
    args = parser.parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    schema = load_schema(repo_root / "config" / "loom-schema.toml")
    results = codegen_all(schema, repo_root)
    drifted: list[str] = []
    for r in results:
        if args.check:
            existing = r.path.read_text(encoding="utf-8") if r.path.exists() else ""
            if existing != r.content:
                drifted.append(str(r.path.relative_to(repo_root)))
            continue
        r.path.parent.mkdir(parents=True, exist_ok=True)
        r.path.write_text(r.content, encoding="utf-8")
    if drifted:
        print("Codegen drift in:", file=sys.stderr)
        for p in drifted:
            print(f"  - {p}", file=sys.stderr)
        print("Run `loom config codegen` to regenerate.", file=sys.stderr)
        return 1
    return 0
