"""shadow management schema

Revision ID: capacity_0001
Revises:
Create Date: 2026-08-10 12:55:58.463717
"""

from __future__ import annotations

from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "capacity_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capacity_allocation_epochs",
        sa.Column("allocation_epoch", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("writer_epoch", sa.BigInteger(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("input_digest", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("complete_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("committed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "input_digest ~ '^[0-9a-f]{64}$'", name="capacity_allocation_input_digest_check"
        ),
        sa.CheckConstraint(
            "status IN ('shadow','failed')", name="capacity_allocation_status_check"
        ),
        sa.CheckConstraint(
            "configuration_epoch > 0", name="capacity_allocation_configuration_epoch_check"
        ),
        sa.CheckConstraint(
            "executable = false", name="capacity_allocation_epoch_shadow_only_check"
        ),
        sa.CheckConstraint("writer_epoch > 0", name="capacity_allocation_writer_epoch_check"),
        sa.PrimaryKeyConstraint("allocation_epoch"),
    )
    op.create_table(
        "capacity_audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_kind", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("event_kind", sa.Text(), nullable=False),
        sa.Column("object_binding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("actor_kind <> ''", name="capacity_audit_actor_kind_check"),
        sa.CheckConstraint("event_kind <> ''", name="capacity_audit_event_kind_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "capacity_authority_state",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("authority_incarnation", sa.UUID(), nullable=False),
        sa.Column("writer_epoch", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("recovery_state", sa.Text(), server_default=sa.text("'shadow'"), nullable=False),
        sa.Column("increase_freeze", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("increase_freeze_reason", sa.Text(), nullable=True),
        sa.Column(
            "executable_new_capacity_ceiling",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "global_pending_slot_ceiling",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "global_pending_job_ceiling",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "global_submission_rate_ceiling",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recovery_state = 'shadow'", name="capacity_authority_recovery_state_check"
        ),
        sa.CheckConstraint(
            "executable_new_capacity_ceiling = 0", name="capacity_authority_shadow_only_check"
        ),
        sa.CheckConstraint(
            "global_pending_slot_ceiling >= 0 AND global_pending_job_ceiling >= 0 AND global_submission_rate_ceiling >= 0",
            name="capacity_authority_limits_check",
        ),
        sa.CheckConstraint("schema_version = 1", name="capacity_authority_schema_check"),
        sa.CheckConstraint("singleton_id = 1", name="capacity_authority_singleton_check"),
        sa.CheckConstraint("writer_epoch >= 0", name="capacity_authority_writer_epoch_check"),
        sa.PrimaryKeyConstraint("singleton_id"),
    )
    op.bulk_insert(
        sa.table(
            "capacity_authority_state",
            sa.column("singleton_id", sa.Integer()),
            sa.column("authority_incarnation", sa.UUID()),
            sa.column("writer_epoch", sa.BigInteger()),
            sa.column("schema_version", sa.Integer()),
            sa.column("recovery_state", sa.Text()),
            sa.column("increase_freeze", sa.Boolean()),
            sa.column("increase_freeze_reason", sa.Text()),
            sa.column("executable_new_capacity_ceiling", sa.BigInteger()),
            sa.column("global_pending_slot_ceiling", sa.BigInteger()),
            sa.column("global_pending_job_ceiling", sa.BigInteger()),
            sa.column("global_submission_rate_ceiling", sa.BigInteger()),
        ),
        [
            {
                "singleton_id": 1,
                "authority_incarnation": uuid4(),
                "writer_epoch": 0,
                "schema_version": 1,
                "recovery_state": "shadow",
                "increase_freeze": True,
                "increase_freeze_reason": "initial_shadow_freeze",
                "executable_new_capacity_ceiling": 0,
                "global_pending_slot_ceiling": 0,
                "global_pending_job_ceiling": 0,
                "global_submission_rate_ceiling": 0,
            }
        ],
    )
    op.create_table(
        "capacity_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("candidate_generation", sa.BigInteger(), nullable=False),
        sa.Column("candidate_digest", sa.Text(), nullable=False),
        sa.Column("source_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("architecture_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("launcher_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attestation_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("protocol_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "candidate_digest ~ '^[0-9a-f]{64}$'", name="capacity_candidate_digest_check"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_id",
            "subject_incarnation",
            "candidate_generation",
            name="capacity_candidate_generation_key",
        ),
    )
    op.create_table(
        "capacity_config_generations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("subject_incarnation", sa.UUID(), nullable=True),
        sa.Column("scope_generation", sa.BigInteger(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'proposed'"), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'fleet' AND subject_id IS NULL AND subject_incarnation IS NULL) OR (scope = 'subject' AND subject_id IS NOT NULL AND subject_incarnation IS NOT NULL)",
            name="capacity_config_binding_check",
        ),
        sa.CheckConstraint("digest ~ '^[0-9a-f]{64}$'", name="capacity_config_digest_check"),
        sa.CheckConstraint("scope IN ('fleet','subject')", name="capacity_config_scope_check"),
        sa.CheckConstraint(
            "state IN ('proposed','active','retired')", name="capacity_config_state_check"
        ),
        sa.CheckConstraint("scope_generation > 0", name="capacity_config_generation_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="capacity_config_idempotency_key"),
        sa.UniqueConstraint(
            "scope",
            "subject_id",
            "subject_incarnation",
            "scope_generation",
            name="capacity_config_scope_generation_key",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "capacity_configuration_epochs",
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("fleet_generation", sa.BigInteger(), nullable=False),
        sa.Column("fleet_digest", sa.Text(), nullable=False),
        sa.Column(
            "subject_generation_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("canonical_digest", sa.Text(), nullable=False),
        sa.Column("activation_idempotency_key", sa.UUID(), nullable=False),
        sa.Column("activation_actor", sa.Text(), nullable=False),
        sa.Column("activation_request_digest", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fleet_digest ~ '^[0-9a-f]{64}$' "
            "AND canonical_digest ~ '^[0-9a-f]{64}$' "
            "AND activation_request_digest ~ '^[0-9a-f]{64}$'",
            name="capacity_configuration_digest_check",
        ),
        sa.CheckConstraint("configuration_epoch > 0", name="capacity_configuration_epoch_check"),
        sa.CheckConstraint(
            "fleet_generation > 0", name="capacity_configuration_fleet_generation_check"
        ),
        sa.PrimaryKeyConstraint("configuration_epoch"),
        sa.UniqueConstraint("activation_idempotency_key"),
        sa.UniqueConstraint("canonical_digest"),
    )
    op.create_table(
        "capacity_demand_reporters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("reporter_incarnation", sa.UUID(), nullable=False),
        sa.Column("configuration_generation", sa.BigInteger(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("high_water", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'current'"), nullable=False),
        sa.Column("last_receipt_time", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_digest", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('current','fenced','equivocal')", name="capacity_demand_reporter_state_check"
        ),
        sa.CheckConstraint("high_water >= 0", name="capacity_demand_reporter_high_water_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_id",
            "subject_incarnation",
            "reporter_incarnation",
            name="capacity_demand_reporter_binding_key",
        ),
    )
    op.create_table(
        "capacity_demand_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("reporter_incarnation", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "database_received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("validity", sa.Text(), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "digest ~ '^[0-9a-f]{64}$'", name="capacity_demand_snapshot_digest_check"
        ),
        sa.CheckConstraint("sequence > 0", name="capacity_demand_snapshot_sequence_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporter_incarnation", "sequence", name="capacity_demand_snapshot_sequence_key"
        ),
    )
    op.create_table(
        "capacity_deployment_generations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("candidate_digest", sa.Text(), nullable=False),
        sa.Column("required_profiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("readiness_state", sa.Text(), nullable=False),
        sa.Column("lifecycle_state", sa.Text(), nullable=False),
        sa.Column("cutover_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "candidate_digest ~ '^[0-9a-f]{64}$'", name="capacity_deployment_candidate_digest_check"
        ),
        sa.CheckConstraint(
            "deployment_generation > 0", name="capacity_deployment_generation_check"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_id",
            "subject_incarnation",
            "deployment_generation",
            name="capacity_deployment_binding_key",
        ),
    )
    op.create_table(
        "capacity_fairness_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.Text(), server_default=sa.text("'shadow'"), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("phase", sa.Text(), nullable=False),
        sa.Column("tier_id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("cursor_id", sa.Text(), nullable=True),
        sa.Column(
            "last_shadow_epoch", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.CheckConstraint("mode = 'shadow'", name="capacity_fairness_state_shadow_only_check"),
        sa.CheckConstraint("phase IN ('minimum','demand')", name="capacity_fairness_phase_check"),
        sa.CheckConstraint(
            "scope IN ('tier_account','account_subject')", name="capacity_fairness_scope_check"
        ),
        sa.CheckConstraint("last_shadow_epoch >= 0", name="capacity_fairness_epoch_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "configuration_epoch",
            "scope",
            "phase",
            "tier_id",
            "account_id",
            "subject_id",
            name="capacity_fairness_scope_key",
        ),
    )
    op.create_table(
        "capacity_observed_commitments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("commitment_identity", sa.Text(), nullable=False),
        sa.Column("source_incarnation", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("subject_incarnation", sa.UUID(), nullable=True),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=True),
        sa.Column("profile_id", sa.Text(), nullable=True),
        sa.Column("profile_generation", sa.BigInteger(), nullable=False),
        sa.Column("profile_digest", sa.Text(), nullable=False),
        sa.Column("shape_id", sa.Text(), nullable=True),
        sa.Column("attempt_id", sa.Text(), nullable=True),
        sa.Column("concurrency_slots", sa.BigInteger(), nullable=True),
        sa.Column("binding_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resource_vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("first_reporter_high_water", sa.BigInteger(), nullable=False),
        sa.Column("last_reporter_high_water", sa.BigInteger(), nullable=False),
        sa.Column("first_receipt_time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_receipt_time", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('claim','physical')", name="capacity_commitment_kind_check"),
        sa.CheckConstraint(
            "state IN ('proposed','accepted','pending','live','draining',"
            "'cancel-pending','submitting-unknown','observed','unknown','quarantined')",
            name="capacity_commitment_state_check",
        ),
        sa.CheckConstraint(
            "profile_generation > 0 AND profile_digest ~ '^[0-9a-f]{64}$'",
            name="capacity_commitment_profile_binding_check",
        ),
        sa.CheckConstraint(
            "(kind = 'claim' AND attempt_id IS NOT NULL AND concurrency_slots > 0) "
            "OR (kind = 'physical' AND attempt_id IS NULL AND concurrency_slots IS NULL)",
            name="capacity_commitment_kind_fields_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "kind",
            "commitment_identity",
            "source_incarnation",
            name="capacity_commitment_source_key",
        ),
    )
    op.create_table(
        "capacity_pool_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("reporter_incarnation", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "database_received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("validity", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "digest ~ '^[0-9a-f]{64}$'", name="capacity_pool_observation_digest_check"
        ),
        sa.CheckConstraint("sequence > 0", name="capacity_pool_observation_sequence_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporter_incarnation", "sequence", name="capacity_pool_observation_sequence_key"
        ),
    )
    op.create_table(
        "capacity_pool_reporters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("reporter_incarnation", sa.UUID(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("high_water", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'current'"), nullable=False),
        sa.Column("last_receipt_time", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_digest", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('current','fenced','equivocal')", name="capacity_pool_reporter_state_check"
        ),
        sa.CheckConstraint("high_water >= 0", name="capacity_pool_reporter_high_water_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pool_id", "reporter_incarnation", name="capacity_pool_reporter_binding_key"
        ),
    )
    op.create_table(
        "capacity_worker_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("profile_generation", sa.BigInteger(), nullable=False),
        sa.Column("profile_digest", sa.Text(), nullable=False),
        sa.Column("shape_catalog", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrowing_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "profile_digest ~ '^[0-9a-f]{64}$'", name="capacity_worker_profile_digest_check"
        ),
        sa.CheckConstraint(
            "deployment_generation > 0 AND pool_generation > 0 AND profile_generation > 0",
            name="capacity_worker_profile_generations_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_id",
            "subject_incarnation",
            "deployment_generation",
            "pool_id",
            "profile_generation",
            name="capacity_worker_profile_binding_key",
        ),
    )
    op.create_table(
        "capacity_account_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("min_reservation_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_surge_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_pending_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_pending_jobs", sa.BigInteger(), nullable=False),
        sa.Column("max_live_subjects", sa.BigInteger(), nullable=False),
        sa.Column("max_builds", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "max_artifact_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "kind IN ('service','owner','owner_template')", name="capacity_account_kind_check"
        ),
        sa.CheckConstraint(
            "min_reservation_slots >= 0 AND max_slots >= min_reservation_slots AND max_surge_slots >= 0 AND max_pending_slots >= 0 AND max_pending_jobs >= 0 AND max_live_subjects > 0 AND max_builds >= 0 AND max_artifact_bytes >= 0",
            name="capacity_account_limits_check",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "configuration_epoch", "account_id", name="capacity_account_epoch_id_key"
        ),
    )
    op.create_table(
        "capacity_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("desired_shapes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("desired_resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("commitments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("drains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowances", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("witness", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mode", sa.Text(), server_default=sa.text("'shadow'"), nullable=False),
        sa.Column("executable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "mode = 'shadow' AND executable = false", name="capacity_allocations_shadow_only_check"
        ),
        sa.ForeignKeyConstraint(
            ["allocation_epoch"],
            ["capacity_allocation_epochs.allocation_epoch"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "allocation_epoch",
            "subject_id",
            "pool_id",
            name="capacity_allocation_epoch_subject_pool_key",
        ),
    )
    op.create_table(
        "capacity_pools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_generation", sa.BigInteger(), nullable=False),
        sa.Column("pool_digest", sa.Text(), nullable=False),
        sa.Column("controller", sa.Text(), nullable=False),
        sa.Column("partition", sa.Text(), nullable=False),
        sa.Column("association", sa.Text(), nullable=False),
        sa.Column("protocol_generation", sa.BigInteger(), nullable=False),
        sa.Column("protocol_digest", sa.Text(), nullable=False),
        sa.Column("topology", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("health", sa.Text(), nullable=False),
        sa.Column("max_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_pending_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_pending_jobs", sa.BigInteger(), nullable=False),
        sa.Column("submission_rate_per_minute", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "pool_digest ~ '^[0-9a-f]{64}$' AND protocol_digest ~ '^[0-9a-f]{64}$'",
            name="capacity_pool_digest_check",
        ),
        sa.CheckConstraint(
            "max_slots >= 0 AND max_pending_slots >= 0 AND max_pending_jobs >= 0 AND submission_rate_per_minute >= 0",
            name="capacity_pool_limits_check",
        ),
        sa.CheckConstraint("pool_generation > 0", name="capacity_pool_generation_check"),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "configuration_epoch", "pool_id", "pool_generation", name="capacity_pool_generation_key"
        ),
    )
    op.create_table(
        "capacity_subjects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("subject_incarnation", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("tier_id", sa.Text(), nullable=False),
        sa.Column("min_slots", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_slots", sa.BigInteger(), nullable=False),
        sa.Column(
            "rollout_surge_slots", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("max_pending_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_pending_jobs", sa.BigInteger(), nullable=False),
        sa.Column("lifecycle_state", sa.Text(), nullable=False),
        sa.Column("candidate_generation", sa.BigInteger(), nullable=False),
        sa.Column("deployment_generation", sa.BigInteger(), nullable=False),
        sa.Column("configuration_generation", sa.BigInteger(), nullable=False),
        sa.Column("demand_reporter_incarnation", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "tier_id IN ('production','staging','development')", name="capacity_subject_tier_check"
        ),
        sa.CheckConstraint(
            "candidate_generation > 0 AND deployment_generation > 0 AND configuration_generation > 0",
            name="capacity_subject_generations_check",
        ),
        sa.CheckConstraint(
            "min_slots >= 0 AND max_slots >= min_slots AND rollout_surge_slots >= 0 AND max_pending_slots >= 0 AND max_pending_jobs >= 0",
            name="capacity_subject_limits_check",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "configuration_epoch",
            "subject_id",
            "subject_incarnation",
            name="capacity_subject_epoch_binding_key",
        ),
    )
    op.create_table(
        "capacity_tiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_epoch", sa.BigInteger(), nullable=False),
        sa.Column("tier_id", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("max_slots", sa.BigInteger(), nullable=False),
        sa.Column("resource_ceilings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_pending_slots", sa.BigInteger(), nullable=False),
        sa.Column("max_pending_jobs", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "tier_id IN ('production','staging','development')", name="capacity_tier_name_check"
        ),
        sa.CheckConstraint(
            "max_slots >= 0 AND max_pending_slots >= 0 AND max_pending_jobs >= 0",
            name="capacity_tier_limits_check",
        ),
        sa.CheckConstraint("priority BETWEEN 0 AND 2", name="capacity_tier_priority_check"),
        sa.ForeignKeyConstraint(
            ["configuration_epoch"],
            ["capacity_configuration_epochs.configuration_epoch"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "configuration_epoch", "priority", name="capacity_tier_epoch_priority_key"
        ),
        sa.UniqueConstraint("configuration_epoch", "tier_id", name="capacity_tier_epoch_id_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capacity_tiers")
    op.drop_table("capacity_subjects")
    op.drop_table("capacity_pools")
    op.drop_table("capacity_allocations")
    op.drop_table("capacity_account_policies")
    op.drop_table("capacity_worker_profiles")
    op.drop_table("capacity_pool_reporters")
    op.drop_table("capacity_pool_observations")
    op.drop_table("capacity_observed_commitments")
    op.drop_table("capacity_fairness_state")
    op.drop_table("capacity_deployment_generations")
    op.drop_table("capacity_demand_snapshots")
    op.drop_table("capacity_demand_reporters")
    op.drop_table("capacity_configuration_epochs")
    op.drop_table("capacity_config_generations")
    op.drop_table("capacity_candidates")
    op.drop_table("capacity_authority_state")
    op.drop_table("capacity_audit_events")
    op.drop_table("capacity_allocation_epochs")
    # ### end Alembic commands ###
