NodeName=trt-gb10-1 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-10 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-11 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-12 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-13 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-14 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-15 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-2 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-3 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-4 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-5 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-6 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-7 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-8 Name=gpu Type=gb10 File=/dev/nvidia0
NodeName=trt-gb10-9 Name=gpu Type=gb10 File=/dev/nvidia0
