ClusterName=trt-gb10
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
GresTypes=gpu
NodeName=trt-gb10-[1-6],trt-gb10-[8-15] CPUs=20 RealMemory=120000 Gres=gpu:gb10:1 State=UNKNOWN
NodeName=trt-gb10-7 CPUs=20 RealMemory=120000 Gres=gpu:gb10:1 State=DOWN
PartitionName=gb10 Nodes=trt-gb10-[1-15] Default=NO MaxTime=1-00:00:00 State=UP OverSubscribe=EXCLUSIVE
