"""Step 12 — release gate (#340, #444)."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from loom_cli.rollout.context import RolloutContext
from loom_cli.rollout.evidence import StepDir
from loom_cli.rollout.steps.base import RunResult
from loom_cli.rollout.steps.candidate_source import (
    CandidateToolingError,
    candidate_loom_argv,
    candidate_loom_cwd,
    candidate_loom_env,
    candidate_relative_path,
    rollout_cluster_config,
)
from loom_cli.rollout.steps.s10_env_state import _profile_path_for
from loom_cli.rollout.steps.subcommand_step import SubcommandStep
from loom_cli.rollout.steps.subprocess_util import run_captured


class ReleaseGateStep(SubcommandStep):
    number = 12
    name = "release-gate"

    def _inputs_fingerprint(self, ctx: RolloutContext) -> dict[str, object]:
        return {
            "cluster_config_sha256": ctx.cluster_config_sha256,
            "environment": ctx.environment,
            "image_tag": ctx.image_tag,
            "namespace": ctx.namespace,
            "resolved_sha": ctx.resolved_sha,
        }

    def release_manifest_path(self, ctx: RolloutContext, step_dir: StepDir) -> Path:
        return step_dir.artifact_path(f"release-manifest-{ctx.image_tag}.json")

    def gb10_status_path(self, ctx: RolloutContext, step_dir: StepDir) -> Path:
        return step_dir.artifact_path(f"gb10-workers-status-{ctx.image_tag}.json")

    def environment_state_check_path(self, step_dir: StepDir) -> Path:
        return (
            step_dir.path.parent
            / "10-env-state"
            / "environment-state-check.json"
        )

    def release_manifest_argv(
        self,
        ctx: RolloutContext,
        step_dir: StepDir,
    ) -> Sequence[str]:
        argv = candidate_loom_argv(
            "cluster",
            "release-manifest",
            "--config",
            str(rollout_cluster_config(ctx, step_dir)),
            "--environment",
            ctx.environment,
            "--image-tag",
            ctx.image_tag,
            "--git-sha",
            ctx.resolved_sha,
            "--output",
            str(self.release_manifest_path(ctx, step_dir)),
        )
        profile = _profile_path_for(ctx, rollout_cluster_config(ctx, step_dir))
        if profile is not None:
            argv.extend([
                "--environment-state-file",
                str(candidate_relative_path(Path(profile), step_dir)),
                "--env-config-version",
                ctx.image_tag,
            ])
        return argv

    def gb10_status_argv(
        self,
        ctx: RolloutContext,
        step_dir: StepDir,
    ) -> Sequence[str]:
        return candidate_loom_argv(
            "admin",
            "gb10-workers",
            "status",
            "--cp-url",
            ctx.cp_url,
            "--environment",
            ctx.environment,
            "--release-image-tag",
            ctx.image_tag,
            "--release-env-config-version",
            ctx.image_tag,
            "--format",
            "json",
        )

    def argv(self, ctx: RolloutContext, step_dir: StepDir) -> Sequence[str]:
        # Point release-gate at the rendered manifest from step 07 and
        # release manifest generated by this rollout step.
        rendered = step_dir.path.parent / "07-render" / "rendered.yaml"
        argv = candidate_loom_argv(
            "cluster",
            "release-gate",
            "--manifest",
            str(self.release_manifest_path(ctx, step_dir)),
            "--namespace",
            ctx.namespace,
            "--environment",
            ctx.environment,
            "--config",
            str(rollout_cluster_config(ctx, step_dir)),
            "--rendered-manifest",
            str(rendered),
            "--gb10-workers-status",
            str(self.gb10_status_path(ctx, step_dir)),
        )
        environment_state_check = self.environment_state_check_path(step_dir)
        if environment_state_check.exists():
            argv.extend(["--environment-state-check", str(environment_state_check)])
        return argv

    def cwd(self, ctx: RolloutContext, step_dir: StepDir) -> Path:
        return candidate_loom_cwd(step_dir)

    def env(
        self,
        ctx: RolloutContext,
        step_dir: StepDir,
    ) -> dict[str, str]:
        return candidate_loom_env(step_dir)

    def _run_impl(self, ctx: RolloutContext, step_dir: StepDir) -> RunResult:
        try:
            cwd = self.cwd(ctx, step_dir)
            env = self.env(ctx, step_dir)
        except CandidateToolingError as exc:
            step_dir.stderr_path().write_text(str(exc) + "\n")
            return RunResult(exit_code=2, error=str(exc))

        manifest_cmd = list(self.release_manifest_argv(ctx, step_dir))
        manifest = run_captured(
            manifest_cmd,
            stdout_log=step_dir.artifact_path("release-manifest.stdout"),
            stderr_log=step_dir.artifact_path("release-manifest.stderr"),
            cwd=cwd,
            env=env,
        )
        artifacts = {
            "release_manifest": str(self.release_manifest_path(ctx, step_dir)),
            "gb10_workers_status": str(self.gb10_status_path(ctx, step_dir)),
        }
        if manifest.returncode != 0:
            return RunResult(
                exit_code=manifest.returncode,
                summary=f"release-manifest exited {manifest.returncode}",
                error=(
                    manifest.stderr.strip().splitlines()[-1]
                    if manifest.stderr.strip()
                    else f"release-manifest exited {manifest.returncode}"
                ),
                artifacts=artifacts,
            )

        gb10_cmd = list(self.gb10_status_argv(ctx, step_dir))
        gb10 = run_captured(
            gb10_cmd,
            stdout_log=self.gb10_status_path(ctx, step_dir),
            stderr_log=step_dir.artifact_path("gb10-workers-status.stderr"),
            cwd=cwd,
            env=env,
            timeout_sec=60,
        )
        if gb10.returncode != 0:
            return RunResult(
                exit_code=gb10.returncode,
                summary=f"gb10-workers status exited {gb10.returncode}",
                error=(
                    gb10.stderr.strip().splitlines()[-1]
                    if gb10.stderr.strip()
                    else f"gb10-workers status exited {gb10.returncode}"
                ),
                artifacts=artifacts,
            )

        gate_cmd = list(self.argv(ctx, step_dir))
        gate = run_captured(
            gate_cmd,
            stdout_log=step_dir.stdout_path(),
            stderr_log=step_dir.stderr_path(),
            cwd=cwd,
            env=env,
        )
        if gate.returncode == 0:
            return RunResult(
                exit_code=0,
                summary="release-manifest + GB10 status + release-gate exited 0",
                artifacts=artifacts,
            )
        if gate.returncode != 0:
            return RunResult(
                exit_code=gate.returncode,
                summary=f"release-gate exited {gate.returncode}",
                error=(
                    gate.stderr.strip().splitlines()[-1]
                    if gate.stderr.strip()
                    else f"release-gate exited {gate.returncode}"
                ),
                artifacts=artifacts,
            )
        raise AssertionError("unreachable release-gate branch")
